-- ============================================================
-- Traduction anglaise des libellés de caractéristiques (product_specs.label_en)
-- 2026-10 — 673 libellés FR -> EN, appliqués à toutes les lignes
-- de caractéristiques qui n'ont pas encore de label_en.
--
-- Sûr à relancer : ne touche que les lignes où label_en IS NULL, donc
-- n'écrase aucune traduction faite à la main (Aurora Avionics, etc.).
-- Les valeurs (value_en) ne sont pas traitées ici.
-- ============================================================

UPDATE product_specs AS s
SET label_en = v.en
FROM (VALUES
  ('Puissance', 'Power'),
  ('Format', 'Form factor'),
  ('Masse', 'Mass'),
  ('Type', 'Type'),
  ('Tension', 'Voltage'),
  ('Applications', 'Applications'),
  ('Chimie', 'Chemistry'),
  ('Interfaces', 'Interfaces'),
  ('Application', 'Application'),
  ('Technologie', 'Technology'),
  ('Fonction', 'Function'),
  ('Interface', 'Interface'),
  ('Rendement', 'Efficiency'),
  ('Bande', 'Band'),
  ('Température', 'Temperature'),
  ('Tension nominale', 'Nominal voltage'),
  ('Architecture', 'Architecture'),
  ('Capacité', 'Capacity'),
  ('Consommation', 'Power consumption'),
  ('Documentation', 'Documentation'),
  ('Énergie', 'Energy'),
  ('Précision', 'Accuracy'),
  ('Refroidissement', 'Cooling'),
  ('Alimentation', 'Power supply'),
  ('Propulsion', 'Propulsion'),
  ('Couple nominal', 'Rated torque'),
  ('Capacite charge utile', 'Payload capacity'),
  ('Cycle de vie', 'Cycle life'),
  ('Débit', 'Data rate'),
  ('Durée de vie', 'Lifetime'),
  ('Fonctions', 'Functions'),
  ('Certification', 'Certification'),
  ('Duree de vie', 'Lifetime'),
  ('Maturité', 'Maturity'),
  ('Protection', 'Protection'),
  ('Capacite LEO', 'LEO capacity'),
  ('Conception', 'Design'),
  ('Couple', 'Torque'),
  ('Redondance', 'Redundancy'),
  ('Autonomie', 'Range'),
  ('Capacite orbite heliosynchrone', 'Sun-synchronous orbit capacity'),
  ('Étanchéité', 'Sealing'),
  ('Champ de vue', 'Field of view'),
  ('Contrôle', 'Control'),
  ('Energie', 'Energy'),
  ('FPGA', 'FPGA'),
  ('Intégration', 'Integration'),
  ('Orbite', 'Orbit'),
  ('Performance', 'Performance'),
  ('Pression max', 'Max pressure'),
  ('Secteurs', 'Sectors'),
  ('Tension d''entrée', 'Input voltage'),
  ('Courant', 'Current'),
  ('Diamètre', 'Diameter'),
  ('Dimensions', 'Dimensions'),
  ('Heritage', 'Heritage'),
  ('Masse au lancement', 'Launch mass'),
  ('Mémoire', 'Memory'),
  ('Programme', 'Program'),
  ('Protocole', 'Protocol'),
  ('Qualification', 'Qualification'),
  ('Tension d''alimentation', 'Supply voltage'),
  ('Tolérance radiations', 'Radiation tolerance'),
  ('Vitesse', 'Speed'),
  ('Bande de fréquence', 'Frequency band'),
  ('Charge rapide DC', 'DC fast charging'),
  ('Communication', 'Communication'),
  ('Compatibilité', 'Compatibility'),
  ('Énergie spécifique', 'Specific energy'),
  ('Plage de mesure', 'Measurement range'),
  ('Pression de service', 'Operating pressure'),
  ('Processeur', 'Processor'),
  ('Production', 'Production'),
  ('Usage', 'Use'),
  ('Bus', 'Bus'),
  ('Champ de vision', 'Field of view'),
  ('Cœur de traitement', 'Processing core'),
  ('Compatible', 'Compatible'),
  ('Composants', 'Components'),
  ('Couple max', 'Max torque'),
  ('Course', 'Stroke'),
  ('Etages', 'Stages'),
  ('Expérience', 'Experience'),
  ('Gamme', 'Range'),
  ('Interconnexion', 'Interconnect'),
  ('Masse max.', 'Max mass'),
  ('Matériau', 'Material'),
  ('Moment angulaire', 'Angular momentum'),
  ('Performance IA', 'AI performance'),
  ('Personnalisation', 'Customization'),
  ('Plage de température', 'Temperature range'),
  ('Plateforme', 'Platform'),
  ('Poids', 'Weight'),
  ('Poids dans l''eau', 'Weight in water'),
  ('Portée', 'Range'),
  ('Précision de cap', 'Heading accuracy'),
  ('Puce', 'Chip'),
  ('Puissance continue', 'Continuous power'),
  ('Puissance de bord', 'Onboard power'),
  ('Puissance nominale', 'Rated power'),
  ('Slots', 'Slots'),
  ('Tension entrée', 'Input voltage'),
  ('Topologie', 'Topology'),
  ('Vitesse maximale', 'Maximum speed'),
  ('Volume charge utile', 'Payload volume'),
  ('Bande passante', 'Bandwidth'),
  ('Batterie', 'Battery'),
  ('BMS', 'BMS'),
  ('Capacite GTO', 'GTO capacity'),
  ('Cellules', 'Cells'),
  ('Charge max', 'Max load'),
  ('Classe d''efficacité', 'Efficiency class'),
  ('Configurations', 'Configurations'),
  ('Conformité', 'Compliance'),
  ('Delta-V disponible', 'Available delta-V'),
  ('Déploiement', 'Deployment'),
  ('Diamètre × longueur', 'Diameter × length'),
  ('Diamètre nominal', 'Nominal diameter'),
  ('Diamètres disponibles', 'Available diameters'),
  ('Domaines', 'Domains'),
  ('Efficacité', 'Efficiency'),
  ('Fabrication', 'Manufacturing'),
  ('Force max', 'Max force'),
  ('Fréquence', 'Frequency'),
  ('Fréquence max', 'Max frequency'),
  ('Gain', 'Gain'),
  ('Génération', 'Generation'),
  ('GPU', 'GPU'),
  ('Impédance', 'Impedance'),
  ('IP', 'IP rating'),
  ('Mission', 'Mission'),
  ('Norme', 'Standard'),
  ('Option', 'Option'),
  ('Options', 'Options'),
  ('Orbites', 'Orbits'),
  ('Origine', 'Origin'),
  ('Plateforme cible', 'Target platform'),
  ('Précision roulis/tangage', 'Roll/pitch accuracy'),
  ('Pression', 'Pressure'),
  ('Profondeur max', 'Max depth'),
  ('Puissance charge utile', 'Payload power'),
  ('Puissance max', 'Max power'),
  ('Radiation', 'Radiation'),
  ('Sécurité', 'Safety'),
  ('SEU', 'SEU'),
  ('Stabilite de biais', 'Bias stability'),
  ('Standard', 'Standard'),
  ('Statut', 'Status'),
  ('Stockage', 'Storage'),
  ('Tension bus DC', 'DC bus voltage'),
  ('Tension de sortie', 'Output voltage'),
  ('Tension système', 'System voltage'),
  ('Tenue radiations', 'Radiation hardness'),
  ('Tolérance SEE', 'SEE tolerance'),
  ('Tolérance TID', 'TID tolerance'),
  ('Unites fabriquees', 'Units manufactured'),
  ('Variantes', 'Variants'),
  ('Accompagnement', 'Support'),
  ('Accréditation', 'Accreditation'),
  ('Actionnement', 'Actuation'),
  ('Angle de pas', 'Step angle'),
  ('Autonomie WLTP', 'WLTP range'),
  ('Avantage', 'Advantage'),
  ('Brevets', 'Patents'),
  ('Capacite batterie', 'Battery capacity'),
  ('Capacite charge utile max.', 'Max payload capacity'),
  ('Certifications', 'Certifications'),
  ('Charge utile', 'Payload'),
  ('Chiffrement', 'Encryption'),
  ('Cible', 'Target'),
  ('Classe', 'Class'),
  ('Classe efficacité', 'Efficiency class'),
  ('Coeur processeur', 'Processor core'),
  ('Configuration', 'Configuration'),
  ('Connecteurs', 'Connectors'),
  ('Connectivité', 'Connectivity'),
  ('Couple continu', 'Continuous torque'),
  ('Couple de sortie max', 'Max output torque'),
  ('Courant nominal', 'Rated current'),
  ('Couverture', 'Coverage'),
  ('Cycles d''insertion', 'Mating cycles'),
  ('Densité énergétique', 'Energy density'),
  ('Duree de mission', 'Mission duration'),
  ('Durée de mission', 'Mission duration'),
  ('Énergie / module', 'Energy per module'),
  ('Entrées capteurs', 'Sensor inputs'),
  ('Environnement', 'Environment'),
  ('Gestion fluide', 'Fluid management'),
  ('Héritage', 'Heritage'),
  ('Heures de vol cumulees', 'Cumulative flight hours'),
  ('Isolation', 'Insulation'),
  ('Isp spécifique', 'Specific Isp'),
  ('Marchés', 'Markets'),
  ('Masse & puissance', 'Mass & power'),
  ('Masse plateforme', 'Platform mass'),
  ('Masse satellite cible', 'Target satellite mass'),
  ('Matériau corps', 'Body material'),
  ('Missions', 'Missions'),
  ('Missions de référence', 'Reference missions'),
  ('Missions heritage', 'Heritage missions'),
  ('Modèle', 'Model'),
  ('Montage', 'Mounting'),
  ('Nombre de contacts', 'Number of contacts'),
  ('Plateformes', 'Platforms'),
  ('Pointage', 'Pointing'),
  ('Ports', 'Ports'),
  ('Poussée nominale', 'Rated thrust'),
  ('Précision de pointage', 'Pointing accuracy'),
  ('Prises', 'Outlets'),
  ('Procédés', 'Processes'),
  ('Propergol', 'Propellant'),
  ('Protocoles', 'Protocols'),
  ('Puissance crête', 'Peak power'),
  ('Puissance crete (entree/sortie)', 'Peak power (input/output)'),
  ('Puissance de sortie', 'Output power'),
  ('Puissance moteur max', 'Max motor power'),
  ('Puissance sortie', 'Output power'),
  ('Qualité composants', 'Component grade'),
  ('Rayon d''action', 'Operating radius'),
  ('Référence programme', 'Program reference'),
  ('Référentiels', 'Reference standards'),
  ('Régulation', 'Regulation'),
  ('Réseau', 'Network'),
  ('Reutilisabilite 1er etage', 'First-stage reusability'),
  ('Robustesse', 'Ruggedness'),
  ('Secteur', 'Sector'),
  ('Sites de production', 'Production sites'),
  ('Sorties chauf.', 'Heater outputs'),
  ('Surcharge admissible', 'Allowable overload'),
  ('Tailles', 'Sizes'),
  ('Temps d''acquisition', 'Acquisition time'),
  ('Tension alimentation', 'Supply voltage'),
  ('Tension max', 'Max voltage'),
  ('Verrouillage', 'Locking'),
  ('Vitesse de rotation', 'Rotational speed'),
  ('Vitesse de sortie max', 'Max output speed'),
  ('Volumes', 'Volumes'),
  ('VRAM', 'VRAM'),
  ('Agilite', 'Agility'),
  ('AI', 'AI'),
  ('Algorithme', 'Algorithm'),
  ('Anti-leurrage', 'Anti-spoofing'),
  ('Appareils démontés', 'Dismantled devices'),
  ('Applications cibles', 'Target applications'),
  ('ARW', 'ARW'),
  ('Assemblage', 'Assembly'),
  ('Autonomie (Large)', 'Range (Large)'),
  ('Autonomie (Pro)', 'Range (Pro)'),
  ('Autonomie max. (Max)', 'Max range (Max)'),
  ('Autonomie récupérée', 'Range recovered'),
  ('Autonomie sans GPS', 'Range without GPS'),
  ('Autonomie WLTP (Comfort Range)', 'WLTP range (Comfort Range)'),
  ('Autonomie WLTP (FWD)', 'WLTP range (FWD)'),
  ('Autonomie WLTP (Long Range)', 'WLTP range (Long Range)'),
  ('Autonomie WLTP (Standard Range)', 'WLTP range (Standard Range)'),
  ('Axes', 'Axes'),
  ('Bande de frequence', 'Frequency band'),
  ('Bandes de frequence', 'Frequency bands'),
  ('Bandes de fréquence', 'Frequency bands'),
  ('Bandes détectées (Gen 2)', 'Detected bands (Gen 2)'),
  ('Bandes supportées', 'Supported bands'),
  ('Batterie (Comfort Range)', 'Battery (Comfort Range)'),
  ('Batterie (Large)', 'Battery (Large)'),
  ('Batterie (Pro)', 'Battery (Pro)'),
  ('Batterie (Standard Range)', 'Battery (Standard Range)'),
  ('Batterie max.', 'Max battery'),
  ('Biais gyroscopique', 'Gyro bias'),
  ('Blindage EMI', 'EMI shielding'),
  ('Boosters d''appoint', 'Strap-on boosters'),
  ('Bruit angulaire', 'Angular noise'),
  ('Bus d''alimentation primaire', 'Primary power bus'),
  ('Bus DC', 'DC bus'),
  ('Bus de distribution', 'Distribution bus'),
  ('Bus de puissance', 'Power bus'),
  ('Bus nominal', 'Nominal bus'),
  ('Bus Omni-P1', 'Omni-P1 bus'),
  ('Bus Omni-P2', 'Omni-P2 bus'),
  ('Bus Omni-P3', 'Omni-P3 bus'),
  ('Canaux', 'Channels'),
  ('Canaux SSPC', 'SSPC channels'),
  ('Capacité de levage (extension max)', 'Lifting capacity (max extension)'),
  ('Capacité de levage (extension min)', 'Lifting capacity (min extension)'),
  ('Capacité de puissance', 'Power capacity'),
  ('Capacité de transport thermique', 'Heat transport capacity'),
  ('Capacite emport (LEO)', 'Payload capacity (LEO)'),
  ('Capacite GEO', 'GEO capacity'),
  ('Capacite GTO (A62 / A64)', 'GTO capacity (A62 / A64)'),
  ('Capacite GTO (config. H3-24)', 'GTO capacity (H3-24 config.)'),
  ('Capacite GTO (perdu / recupere)', 'GTO capacity (expended / recovered)'),
  ('Capacite LEO (200 km)', 'LEO capacity (200 km)'),
  ('Capacite LEO (45°)', 'LEO capacity (45°)'),
  ('Capacite LEO (A62 / A64)', 'LEO capacity (A62 / A64)'),
  ('Capacite LEO (config. H3-24)', 'LEO capacity (H3-24 config.)'),
  ('Capacite LEO (depuis Kourou)', 'LEO capacity (from Kourou)'),
  ('Capacite LEO (perdu / recupere)', 'LEO capacity (expended / recovered)'),
  ('Capacite LEO (reutilisable / perdu)', 'LEO capacity (reusable / expended)'),
  ('Capacite max. LEO (700 km, 45°)', 'Max LEO capacity (700 km, 45°)'),
  ('Capacité mémoire de masse (par module)', 'Mass memory capacity (per module)'),
  ('Capacite orbite heliosynchrone (500 km)', 'Sun-synchronous orbit capacity (500 km)'),
  ('Capacite orbite heliosynchrone (depuis Andøya)', 'Sun-synchronous orbit capacity (from Andøya)'),
  ('Capacite orbite heliosynchrone (perdu)', 'Sun-synchronous orbit capacity (expended)'),
  ('Capacite orbite heliosynchrone (reutilisable)', 'Sun-synchronous orbit capacity (reusable)'),
  ('Capacite orbite polaire', 'Polar orbit capacity'),
  ('Capacité par taille', 'Capacity by size'),
  ('Capacité production', 'Production capacity'),
  ('Capacité usine (2028)', 'Factory capacity (2028)'),
  ('Capacité usine (initiale → 2030)', 'Factory capacity (initial → 2030)'),
  ('Capteur', 'Sensor'),
  ('Capteur optique', 'Optical sensor'),
  ('Capteurs d''attitude intégrés', 'Integrated attitude sensors'),
  ('Capteurs de température', 'Temperature sensors'),
  ('Capteurs gyro/accél', 'Gyro/accelerometer sensors'),
  ('Cas d''usage', 'Use cases'),
  ('Catégorie', 'Category'),
  ('Cellules en série', 'Cells in series'),
  ('Cellules gérées', 'Managed cells'),
  ('Certif. aéro', 'Aerospace certification'),
  ('Certification mécaniciens', 'Mechanic certification'),
  ('Certification qualité', 'Quality certification'),
  ('Champ de vision nominal', 'Nominal field of view'),
  ('Charge', 'Charging'),
  ('Charge utile (armement/mission)', 'Payload (weapons/mission)'),
  ('Charge utile associée', 'Associated payload'),
  ('Charge utile max.', 'Max payload'),
  ('Charge utile robot', 'Robot payload'),
  ('Charges utiles hebergees (1er vol)', 'Hosted payloads (first flight)'),
  ('Chimie & C-rate', 'Chemistry & C-rate'),
  ('Chimie & fabrication', 'Chemistry & manufacturing'),
  ('Chimies compatibles', 'Compatible chemistries'),
  ('Classe de masse', 'Mass class'),
  ('Client', 'Customer'),
  ('Co-développement', 'Co-development'),
  ('Cœurs', 'Cores'),
  ('Cœurs RISC-V', 'RISC-V cores'),
  ('Communications', 'Communications'),
  ('Compatibilite', 'Compatibility'),
  ('Compatibilité onduleurs ESS', 'ESS inverter compatibility'),
  ('Composants associés requis', 'Required associated components'),
  ('Conditions d''emploi', 'Operating conditions'),
  ('Conducteurs', 'Conductors'),
  ('Configurations tension', 'Voltage configurations'),
  ('Constellations', 'Constellations'),
  ('Constellations supportées', 'Supported constellations'),
  ('Construction', 'Construction'),
  ('Contact', 'Contact'),
  ('Contact tournant', 'Rotating contact'),
  ('Conversion', 'Conversion'),
  ('Couple (gamme bevel g500-B)', 'Torque (bevel g500-B range)'),
  ('Couple à l''arrêt', 'Stall torque'),
  ('Couple au poignet', 'Wrist torque'),
  ('Couple de décollage', 'Breakaway torque'),
  ('Couple de maintien', 'Holding torque'),
  ('Couple détentif', 'Detent torque'),
  ('Couple maximal', 'Maximum torque'),
  ('Couple pas-à-pas hybride', 'Hybrid stepper torque'),
  ('Courant charge max', 'Max charge current'),
  ('Courant continu', 'Continuous current'),
  ('Courant de phase', 'Phase current'),
  ('Courant entrée', 'Input current'),
  ('Courant max continu', 'Max continuous current'),
  ('Cyclabilité', 'Cycle capability'),
  ('Cyclage', 'Cycling'),
  ('Cycle de vie mission', 'Mission life cycle'),
  ('Cycles', 'Cycles'),
  ('Debit', 'Data rate'),
  ('Débit (par module)', 'Throughput (per module)'),
  ('Debit charge utile max', 'Max payload data rate'),
  ('Débit de données', 'Data rate'),
  ('Debit descendant (X-band)', 'Downlink data rate (X-band)'),
  ('Débit descendant / montant', 'Downlink / uplink data rate'),
  ('Debit descendant max', 'Max downlink data rate'),
  ('Débit max', 'Max flow rate'),
  ('Débit nominal', 'Rated flow rate'),
  ('Délai de production', 'Production lead time'),
  ('Densité énergie', 'Energy density'),
  ('Densité nanotubes', 'Nanotube density'),
  ('Dérive gyroscopique', 'Gyro drift'),
  ('Dexterité', 'Dexterity'),
  ('Diagnostic', 'Diagnostics'),
  ('Dimension max', 'Max dimension'),
  ('Dimensions (MTi-1)', 'Dimensions (MTi-1)'),
  ('DOD LEO', 'LEO DOD'),
  ('Données trackées', 'Tracked data'),
  ('Duree de mission visee', 'Target mission duration'),
  ('Duree de vie GEO / Deep Space', 'GEO / deep space lifetime'),
  ('Duree de vie LEO', 'LEO lifetime'),
  ('Durée de vie qualifiée', 'Qualified lifetime'),
  ('Durée de vie visée', 'Target lifetime'),
  ('Économie d''énergie constatée', 'Observed energy savings'),
  ('Effectifs groupe', 'Group headcount'),
  ('Electronique', 'Electronics'),
  ('Émission', 'Emission'),
  ('Empreinte carbone', 'Carbon footprint'),
  ('Encodeur', 'Encoder'),
  ('Encombrement', 'Footprint'),
  ('Énergie pack', 'Pack energy'),
  ('Entrées MPPT', 'MPPT inputs'),
  ('Env.', 'Env.'),
  ('Envergure', 'Wingspan'),
  ('Épaisseur de couche min.', 'Min layer thickness'),
  ('Équivalent véhicules/an', 'Vehicle equivalent per year'),
  ('Exclusion solaire', 'Sun exclusion'),
  ('Expérience orbitale', 'Orbital experience'),
  ('Fiabilité', 'Reliability'),
  ('Fonctionnement', 'Operation'),
  ('Fonctions additionnelles', 'Additional functions'),
  ('Force', 'Force'),
  ('Force continue', 'Continuous force'),
  ('Force maximale', 'Maximum force'),
  ('Format CubeSat', 'CubeSat format'),
  ('Format de base', 'Base format'),
  ('Format image', 'Image format'),
  ('Formats', 'Formats'),
  ('Formats disponibles', 'Available formats'),
  ('Fréquence de mise à jour', 'Update rate'),
  ('Fréquence de scan', 'Scan frequency'),
  ('Fréquence de sortie', 'Output frequency'),
  ('Fréquence radar', 'Radar frequency'),
  ('Fréquence radio', 'Radio frequency'),
  ('G/T et EIRP', 'G/T and EIRP'),
  ('Gamme de masse', 'Mass range'),
  ('Gamme de masse (societe)', 'Mass range (company)'),
  ('Garantie', 'Warranty'),
  ('Garantie performance PV', 'PV performance warranty'),
  ('Geneneration', 'Generation'),
  ('Generation', 'Generation'),
  ('GPIO', 'GPIO'),
  ('Grade de balance', 'Balance grade'),
  ('Hauteur', 'Height'),
  ('Hauteur de rack max.', 'Max rack height'),
  ('Heritage de vol', 'Flight heritage'),
  ('Heritage vol', 'Flight heritage'),
  ('Héritage vol', 'Flight heritage'),
  ('Historique de vol cumulé', 'Cumulative flight history'),
  ('Hystérésis', 'Hysteresis'),
  ('Installations dans le monde', 'Installations worldwide'),
  ('Interface bus', 'Bus interface'),
  ('Interface cam.', 'Camera interface'),
  ('Interface CAN', 'CAN interface'),
  ('Interface data', 'Data interface'),
  ('Interface lanceur', 'Launcher interface'),
  ('Interfaces de communication', 'Communication interfaces'),
  ('Largeur d''allée requise', 'Required aisle width'),
  ('Laser(s)', 'Laser(s)'),
  ('Launchers', 'Launchers'),
  ('Liaison inter-satellite optique', 'Optical inter-satellite link'),
  ('Lieu de production', 'Production location'),
  ('Localisation', 'Location'),
  ('Longueur câbles', 'Cable length'),
  ('Longueur d''onde', 'Wavelength'),
  ('Longueur déployée', 'Deployed length'),
  ('Lubrification', 'Lubrication'),
  ('Magnétomètres', 'Magnetometers'),
  ('Maintenance', 'Maintenance'),
  ('Manifestes', 'Manifests'),
  ('Marché', 'Market'),
  ('Marché cible', 'Target market'),
  ('Masse (generation actuelle)', 'Mass (current generation)'),
  ('Masse charge utile', 'Payload mass'),
  ('Masse charge utile max.', 'Max payload mass'),
  ('Masse directe en orbite geo (GSO)', 'Direct-to-GEO mass (GSO)'),
  ('Masse du bus', 'Bus mass'),
  ('Masse en orbite de transfert (GTO)', 'Mass to transfer orbit (GTO)'),
  ('Masse humide max.', 'Max wet mass'),
  ('Masse max. au décollage', 'Max takeoff mass'),
  ('Masse propulseur', 'Thruster mass'),
  ('Masse satellites', 'Satellite mass'),
  ('Masse spécifique', 'Specific mass'),
  ('Masse totale', 'Total mass'),
  ('Matériau / fluide caloporteur', 'Material / heat-transfer fluid'),
  ('Matériaux compatibles', 'Compatible materials'),
  ('Maturite technologique', 'Technology readiness'),
  ('Mémoire non volatile', 'Non-volatile memory'),
  ('Mesure courant (shunt)', 'Current measurement (shunt)'),
  ('Mesure tension cellule', 'Cell voltage measurement'),
  ('Mesures', 'Measurements'),
  ('Mise en service', 'Entry into service'),
  ('Mission de référence', 'Reference mission'),
  ('Mode de fonctionnement', 'Operating mode'),
  ('Modèle de référence AF130', 'Reference model AF130'),
  ('Modulation', 'Modulation'),
  ('Modulations supportées', 'Supported modulations'),
  ('Moment magnétique', 'Magnetic moment'),
  ('Momentum nominal', 'Nominal momentum'),
  ('Motorisation', 'Powertrain'),
  ('MPPT', 'MPPT'),
  ('Nb contacts', 'No. of contacts'),
  ('Niveaux', 'Levels'),
  ('Nombre de connecteurs', 'Number of connectors'),
  ('Nombre de voies', 'Number of channels'),
  ('Norme de fabrication', 'Manufacturing standard'),
  ('Normes', 'Standards'),
  ('Normes militaires', 'Military standards'),
  ('Notification expédition', 'Shipping notification'),
  ('Objectif', 'Objective'),
  ('Optique', 'Optics'),
  ('Orbites compatibles', 'Compatible orbits'),
  ('OS', 'OS'),
  ('Partenaire de développement', 'Development partner'),
  ('Particularité', 'Special feature'),
  ('PCIe/CSI', 'PCIe/CSI'),
  ('Pièces remises en service', 'Parts returned to service'),
  ('Pile à combustible', 'Fuel cell'),
  ('Pilotage', 'Control'),
  ('Pinces disponibles', 'Available grippers'),
  ('Pipeline', 'Pipeline'),
  ('Plage', 'Range'),
  ('Plage altitude', 'Altitude range'),
  ('Plage de configuration charge utile', 'Payload configuration range'),
  ('Plage de débit (gamme standard)', 'Flow rate range (standard range)'),
  ('Plage de puissance', 'Power range'),
  ('Plage de puissance (famille)', 'Power range (family)'),
  ('Plage de sortie', 'Output range'),
  ('Plage de température de fonctionnement', 'Operating temperature range'),
  ('Plage de température opérationnelle', 'Operating temperature range'),
  ('Plage de tension', 'Voltage range'),
  ('Plage de tension par cellule', 'Voltage range per cell'),
  ('Plage sortie', 'Output range'),
  ('Plateforme base', 'Base platform'),
  ('Plateformes cibles', 'Target platforms'),
  ('Polarisation', 'Polarization'),
  ('Pôles', 'Poles'),
  ('Portée de détection', 'Detection range'),
  ('Portée maximale', 'Maximum range'),
  ('Portfolio', 'Portfolio'),
  ('Position gamme', 'Range positioning'),
  ('Précision altitude', 'Altitude accuracy'),
  ('Précision attitude', 'Attitude accuracy'),
  ('Precision de pointage (ADCS)', 'Pointing accuracy (ADCS)'),
  ('Précision de position', 'Position accuracy'),
  ('Précision de vitesse', 'Velocity accuracy'),
  ('Précision DVL-aidée (%TD CEP50)', 'DVL-aided accuracy (%TD CEP50)'),
  ('Précision position', 'Position accuracy'),
  ('Précision SOC', 'SOC accuracy'),
  ('Précision temporelle', 'Timing accuracy'),
  ('Présence', 'Presence'),
  ('Pression air', 'Air pressure'),
  ('Prestation', 'Service'),
  ('Principe', 'Principle'),
  ('Production quotidienne', 'Daily production'),
  ('Produits', 'Products'),
  ('Profondeur max.', 'Max depth'),
  ('Propulsion 1er etage', 'First-stage propulsion'),
  ('Protection des données', 'Data protection'),
  ('Protection SEU', 'SEU protection'),
  ('Puissance (BEV)', 'Power (BEV)'),
  ('Puissance (modèle de référence)', 'Power (reference model)'),
  ('Puissance (plateforme Augmented)', 'Power (Augmented platform)'),
  ('Puissance / couple max (fiche complète)', 'Max power / torque (full datasheet)'),
  ('Puissance chargeur', 'Charger power'),
  ('Puissance cible', 'Target power'),
  ('Puissance crête (48 V)', 'Peak power (48 V)'),
  ('Puissance crete (version renforcee)', 'Peak power (reinforced version)'),
  ('Puissance crete disponible', 'Available peak power'),
  ('Puissance d''émission', 'Transmit power'),
  ('Puissance d''entrée min.', 'Min input power'),
  ('Puissance électrolyseur', 'Electrolyzer power'),
  ('Puissance gérée', 'Managed power'),
  ('Puissance moteur (Comfort Range)', 'Motor power (Comfort Range)'),
  ('Puissance moteur (Standard Range)', 'Motor power (Standard Range)'),
  ('Puissance moyenne charge utile', 'Average payload power'),
  ('Puissance moyenne orbitale', 'Orbit-average power'),
  ('Puissance nominale / crête', 'Rated / peak power'),
  ('Puissance RF', 'RF power'),
  ('Puissance système', 'System power'),
  ('Puissance transférée', 'Transferred power'),
  ('Qubits (génération Gamma)', 'Qubits (Gamma generation)'),
  ('Radiations', 'Radiation'),
  ('RAM', 'RAM'),
  ('RAM OBC', 'OBC RAM'),
  ('Rapport de réduction', 'Reduction ratio'),
  ('Recadrage', 'Reframing'),
  ('Reconditionnement', 'Refurbishment'),
  ('Reconfigurabilite', 'Reconfigurability'),
  ('Réduction GES vs PET vierge', 'GHG reduction vs virgin PET'),
  ('Référence en vol', 'Flight reference'),
  ('Reference programme', 'Program reference'),
  ('Référence vol', 'Flight reference'),
  ('Références installées', 'Installed references'),
  ('Rendement moyen', 'Average efficiency'),
  ('Répétabilité', 'Repeatability'),
  ('Résistance', 'Resistance'),
  ('Résistance contact', 'Contact resistance'),
  ('Résolutions', 'Resolutions'),
  ('Routage', 'Routing'),
  ('Secteurs servis', 'Sectors served'),
  ('Sections', 'Cross-sections'),
  ('Segment', 'Segment'),
  ('Segments', 'Segments'),
  ('Séquencement', 'Sequencing'),
  ('SERDES', 'SERDES'),
  ('Services', 'Services'),
  ('Shunt inclus', 'Shunt included'),
  ('Site de lancement prevu', 'Planned launch site'),
  ('Sites français', 'French sites'),
  ('Sorties', 'Outputs'),
  ('Source de données', 'Data source'),
  ('SpaceWire', 'SpaceWire'),
  ('Spectre', 'Spectrum'),
  ('Stabilité', 'Stability'),
  ('Stabilité de régulation', 'Regulation stability'),
  ('Stabilité long terme', 'Long-term stability'),
  ('Standards', 'Standards'),
  ('Standards compatibles', 'Compatible standards'),
  ('Standards supportés', 'Supported standards'),
  ('Stérilisation', 'Sterilization'),
  ('Stockage embarque', 'Onboard storage'),
  ('Stockage energie', 'Energy storage'),
  ('Stockage logs', 'Log storage'),
  ('Surcharge', 'Overload'),
  ('Système d''exploitation', 'Operating system'),
  ('Système de fichiers', 'File system'),
  ('Taille', 'Size'),
  ('Taux de dépolymérisation', 'Depolymerization rate'),
  ('Technologie de commutation', 'Switching technology'),
  ('Télémesure', 'Telemetry'),
  ('Temperature', 'Temperature'),
  ('Température de fonctionnement', 'Operating temperature'),
  ('Température jonction', 'Junction temperature'),
  ('Température opér.', 'Operating temp.'),
  ('Température opérationnelle', 'Operating temperature'),
  ('Temps coupure', 'Cut-off time'),
  ('Temps d''activation', 'Activation time'),
  ('Temps de déploiement', 'Deployment time'),
  ('Temps de manœuvre', 'Maneuver time'),
  ('Temps de positionnement', 'Positioning time'),
  ('Temps de réponse', 'Response time'),
  ('Temps de tenue court-circuit', 'Short-circuit withstand time'),
  ('Tension (16S)', 'Voltage (16S)'),
  ('Tension batt.', 'Battery voltage'),
  ('Tension bus', 'Bus voltage'),
  ('Tension d''entrée/sortie', 'Input/output voltage'),
  ('Tension du système', 'System voltage'),
  ('Tension nominale (ex. MCS12L41)', 'Nominal voltage (e.g. MCS12L41)'),
  ('Tension pack', 'Pack voltage'),
  ('Tension panneau max', 'Max panel voltage'),
  ('Tension réseau de bord', 'Onboard network voltage'),
  ('Tenue aux chocs', 'Shock resistance'),
  ('Tenue brouillard salin', 'Salt spray resistance'),
  ('Tenue thermique', 'Thermal resistance'),
  ('TM/TC', 'TM/TC'),
  ('Tolérance pannes', 'Fault tolerance'),
  ('Tolérance radiation', 'Radiation tolerance'),
  ('Traçabilité', 'Traceability'),
  ('Traitement embarqué', 'Onboard processing'),
  ('Transfert de puissance', 'Power transfer'),
  ('Transpondeurs actifs', 'Active transponders'),
  ('TRL', 'TRL'),
  ('TWTA radiatifs (telecom)', 'Radiation-cooled TWTAs (telecom)'),
  ('Type de rotor', 'Rotor type'),
  ('Type fibre', 'Fiber type'),
  ('Unites en orbite', 'Units in orbit'),
  ('Unites en vol', 'Units in flight'),
  ('Unités en vol', 'Units in flight'),
  ('Unités produites', 'Units produced'),
  ('Variante', 'Variant'),
  ('Vérification erreurs', 'Error checking'),
  ('Vibration aléatoire', 'Random vibration'),
  ('Vibrations', 'Vibration'),
  ('Vibrations aléatoires', 'Random vibration'),
  ('Vitesse (AKM2G)', 'Speed (AKM2G)'),
  ('Vitesse & protection', 'Speed & protection'),
  ('Vitesse & rendement', 'Speed & efficiency'),
  ('Vitesse charge/décharge', 'Charge/discharge rate'),
  ('Vitesse commutation', 'Switching speed'),
  ('Vitesse linéaire', 'Linear speed'),
  ('Vitesse max', 'Max speed'),
  ('Vitesse max par taille (AKM2G)', 'Max speed by size (AKM2G)'),
  ('Vitesse opér.', 'Operating speed'),
  ('Vitesse robot', 'Robot speed'),
  ('Volume', 'Volume'),
  ('Volume de fabrication', 'Manufacturing volume'),
  ('Volume produit', 'Volume produced')
) AS v(fr, en)
WHERE s.label = v.fr
  AND s.label_en IS NULL;

-- Contrôle : nombre de lignes encore sans libellé anglais (doit être ~0).
SELECT count(*) AS lignes_sans_label_en FROM product_specs WHERE label_en IS NULL;
