-- ============================================================
-- Noms de produits en anglais (products.name_en) — 2026-10
--
-- 1. Ajoute la colonne products.name_en (NULL par défaut : le site retombe
--    sur le nom d'origine tant qu'elle est vide).
-- 2. L'expose dans la vue v_products_full, EN FIN de liste (Postgres refuse
--    un CREATE OR REPLACE VIEW qui décale les colonnes, erreur 42P16). Au lieu
--    de recopier la définition de la vue, on la lit (pg_get_viewdef) et on y
--    ajoute p.name_en : elle reste identique à ce qui tourne en base.
--    Les fonctions get_products_page / get_product_by_id / get_products_by_company
--    sont `returns setof v_products_full` : elles héritent de la colonne.
-- 3. Renseigne 350 noms (UPDATE par nom, une seule fois par nom).
--
-- Sûr à relancer : la colonne et la vue ne sont modifiées que si besoin, et les
-- UPDATE ne remplissent que les name_en encore vides.
-- ============================================================

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS name_en TEXT;

DO $$
DECLARE
  def text;
BEGIN
  def := pg_get_viewdef('public.v_products_full'::regclass, true);
  IF def ~* 'name_en' THEN
    RAISE NOTICE 'v_products_full expose deja name_en, rien a faire.';
    RETURN;
  END IF;
  def := regexp_replace(def, ';\s*$', '');
  IF def !~* '\sFROM (public\.)?products p\s' THEN
    RAISE EXCEPTION 'Structure inattendue de v_products_full (FROM products p introuvable) : envoie-moi le resultat de pg_get_viewdef.';
  END IF;
  def := regexp_replace(def, '(\s)FROM ((public\.)?products p)(\s)', ', p.name_en\1FROM \2\4', 'i');
  EXECUTE 'CREATE OR REPLACE VIEW public.v_products_full AS ' || def;
END $$;

UPDATE public.products AS p
SET name_en = v.en
FROM (VALUES
  ('1N HPGP — Propulseur vert LEO', '1N HPGP — Green thruster for LEO'),
  ('5N HPGP — Contrôle d''orbite', '5N HPGP — Orbit control'),
  ('ACS880 — 0,75–5 600 kW', 'ACS880 — 0.75–5,600 kW'),
  ('Actionneur de déploiement panneau solaire', 'Solar panel deployment actuator'),
  ('Actionneur électrique de tourelle EA-600', 'EA-600 electric turret actuator'),
  ('Actionneur électrique de vanne marine', 'Marine valve electric actuator'),
  ('Actionneur électrique et vanne process', 'Electric actuator and process valve'),
  ('Actionneur pneumatique série GP', 'GP series pneumatic actuator'),
  ('Actionneurs mécatroniques BLDC & pas-à-pas', 'BLDC & stepper mechatronic actuators'),
  ('AKM — Servomoteur synchrone', 'AKM — Synchronous servomotor'),
  ('AKMH — Servomoteur hygiénique inox', 'AKMH — Stainless-steel hygienic servomotor'),
  ('Altimètre radar RA-200', 'RA-200 radar altimeter'),
  ('Amplificateur RF haute puissance PA-500', 'PA-500 high-power RF amplifier'),
  ('Amplificateur RF large bande AB-150', 'AB-150 wideband RF amplifier'),
  ('Antelope — unité de traitement de données / OBC', 'Antelope — data processing unit / OBC'),
  ('Antenne à réseau réflecteur', 'Reflectarray antenna'),
  ('Antenne bande X à faisceau large', 'Wide-beam X-band antenna'),
  ('Antenne bande X haut gain', 'High-gain X-band antenna'),
  ('Antenne compacte bande X', 'Compact X-band antenna'),
  ('Antenne compacte bande X bi-polarisation', 'Dual-polarization compact X-band antenna'),
  ('Antenne cornet à crêtes croisées', 'Quad-ridged horn antenna'),
  ('Antenne de station sol partagée', 'Shared ground station antenna'),
  ('Antenne déployable nanosatellite', 'Nanosatellite deployable antenna'),
  ('Antenne GNSS bandes L1/E1', 'L1/E1-band GNSS antenna'),
  ('Antenne GNSS multi-bandes', 'Multi-band GNSS antenna'),
  ('Antenne GNSS multi-bandes avec LNA intégré', 'Multi-band GNSS antenna with integrated LNA'),
  ('Antenne hélice quadrifilaire', 'Quadrifilar helix antenna'),
  ('Antenne lanceur bande S', 'S-band launcher antenna'),
  ('Antenne lanceur GNSS multi-bandes', 'Multi-band GNSS launcher antenna'),
  ('Antenne réseau à guide d''ondes à fentes', 'Slotted waveguide array antenna'),
  ('Antenne réseau à rayonnement direct', 'Direct-radiating array antenna'),
  ('Antenne SATCOM Ku-Band SAT-450', 'SAT-450 Ku-Band SATCOM antenna'),
  ('Antenne tactique repliable AT-150', 'AT-150 foldable tactical antenna'),
  ('Antenne TT&C bande Ka', 'Ka-band TT&C antenna'),
  ('Antenne TT&C bande S', 'S-band TT&C antenna'),
  ('Antenne TT&C bande S compacte', 'Compact S-band TT&C antenna'),
  ('Antennes compactes large bande', 'Compact wideband antennas'),
  ('Assemblage de cartes électroniques CMS/THT', 'SMT/THT electronic board assembly'),
  ('Assemblage et intégration électronique en série', 'Series electronic assembly and integration'),
  ('Assistance technique et R&D externalisée', 'Technical assistance and outsourced R&D'),
  ('Assistance technique et recrutement ingénieurs', 'Technical assistance and engineer recruitment'),
  ('ASTREKa — Terminal de communication satellite Ka-band', 'ASTREKa — Ka-band satellite communication terminal'),
  ('Axial Flux EDU — Moteur de traction véhicules électriques', 'Axial Flux EDU — Electric vehicle traction motor'),
  ('BackPlane SpaceVPX — Backplane haute vitesse complet', 'BackPlane SpaceVPX — Complete high-speed backplane'),
  ('Banc de test bande GNSS multi-bandes', 'Multi-band GNSS test bench'),
  ('Banc de test bande S TT&C', 'S-band TT&C test bench'),
  ('Banc de test bande X', 'X-band test bench'),
  ('Batterie primaire Li-SOCl2 spatiale', 'Space Li-SOCl2 primary battery'),
  ('Batterie thermique pour défense', 'Thermal battery for defense'),
  ('Bloc de vannes pneumatiques PV-220', 'PV-220 pneumatic valve block'),
  ('BMS pour batteries lithium-ion', 'BMS for lithium-ion batteries'),
  ('Borne de recharge ultra-rapide', 'Ultra-fast charging station'),
  ('BTRY 1S4P — batterie solid-state ultra-fine', 'BTRY 1S4P — ultra-thin solid-state battery'),
  ('BX4 — Moteur brushless 4 pôles', 'BX4 — 4-pole brushless motor'),
  ('Câblage et faisceaux électriques', 'Wiring and electrical harnesses'),
  ('Câble assemblé médical série M', 'M-series medical cable assembly'),
  ('Calculateur de données air ADC-3000', 'ADC-3000 air data computer'),
  ('Calculateur embarqué OBC-P4', 'OBC-P4 onboard computer'),
  ('Caméra satellite s.LDU.345 (5–51 MP, PAN/MS/HS)', 's.LDU.345 satellite camera (5–51 MP, PAN/MS/HS)'),
  ('Capteur de débit FLOWave SE30', 'FLOWave SE30 flow sensor'),
  ('Capteur de mesure industriel', 'Industrial measurement sensor'),
  ('Capteur de pression CPS pour HVAC', 'CPS pressure sensor for HVAC'),
  ('Capteur de pression HV', 'HV pressure sensor'),
  ('Capteur IoT sans fil miniature', 'Miniature wireless IoT sensor'),
  ('Capteur laser de niveau pour silo', 'Silo laser level sensor'),
  ('Capteur stellaire AOCS — Star Tracker', 'AOCS Star Tracker'),
  ('Capteurs pour environnements sévères', 'Sensors for harsh environments'),
  ('CAVUSmartTags® — Système de traçabilité', 'CAVUSmartTags® — Traceability system'),
  ('CDH-FS — Système C&DH redondant flight-proven', 'CDH-FS — Flight-proven redundant C&DH system'),
  ('CDH1 — Module C&DH baseline', 'CDH1 — Baseline C&DH module'),
  ('Cellule cylindrique 2170', '2170 cylindrical cell'),
  ('Cellule LMP tout-solide', 'All-solid-state LMP cell'),
  ('Cellule NMC — Gigafactory', 'NMC cell — Gigafactory'),
  ('Cellule NMC bas-carbone', 'Low-carbon NMC cell'),
  ('Cellule prismatique 94Ah NMC', '94Ah NMC prismatic cell'),
  ('Cellule solaire spatiale GaAs 30% Triple-Junction', '30% GaAs Triple-Junction space solar cell'),
  ('Cellule solaire spatiale GaAs 32% Triple-Junction', '32% GaAs Triple-Junction space solar cell'),
  ('Centrale inertielle IMU-HG4930', 'IMU-HG4930 inertial measurement unit'),
  ('CMP.. — Servomoteur synchrone', 'CMP.. — Synchronous servomotor'),
  ('Composant optique infrarouge industriel', 'Industrial infrared optical component'),
  ('Conception de bancs d''essais et industrialisation', 'Test bench design and industrialization'),
  ('Connecteur circulaire sous-marin', 'Underwater circular connector'),
  ('Connecteur et protection de circuit', 'Connector and circuit protection'),
  ('Connecteur fibre optique militaire', 'Military fiber-optic connector'),
  ('Connecteur MQS automobile', 'Automotive MQS connector'),
  ('Connecteur push-pull série K', 'K-series push-pull connector'),
  ('Connecteur RF durci RFC-7', 'RFC-7 ruggedized RF connector'),
  ('Connecteur RF SMA durci', 'Ruggedized SMA RF connector'),
  ('Connecteurs haute fiabilité multi-marques', 'Multi-brand high-reliability connectors'),
  ('Conseil en ingénierie et performance opérationnelle', 'Engineering consulting and operational performance'),
  ('Contrôle de mission en tant que service', 'Mission control as a service'),
  ('Convertisseur bas bruit (LNB)', 'Low-noise block converter (LNB)'),
  ('Convertisseur DC/DC BDC546', 'BDC546 DC/DC converter'),
  ('Convertisseur DC/DC bidirectionnel (BESS / V2G)', 'Bidirectional DC/DC converter (BESS / V2G)'),
  ('Convertisseur DC/DC haute tension', 'High-voltage DC/DC converter'),
  ('Convertisseur de puissance sur mesure', 'Custom power converter'),
  ('Convertisseur de traction ONIX', 'ONIX traction converter'),
  ('Corvus Blue Whale — ESS modulaire', 'Corvus Blue Whale — Modular ESS'),
  ('Corvus Dolphin — ESS haute densité', 'Corvus Dolphin — High-density ESS'),
  ('CPM90 — Moteur/générateur brushless', 'CPM90 — Brushless motor/generator'),
  ('CS-HV500 Capteur ±500A', 'CS-HV500 ±500A sensor'),
  ('cyber® dynamic line — Servomoteurs compacts', 'cyber® dynamic line — Compact servomotors'),
  ('cyber® force line — Actionneurs linéaires', 'cyber® force line — Linear actuators'),
  ('D633 Servovanne 2 étages', 'D633 2-stage servo valve'),
  ('DC-Micromoteur Série 1016 SR', '1016 SR Series DC micromotor'),
  ('DC-Micromoteur Série 1724 SR', '1724 SR Series DC micromotor'),
  ('DC-Micromoteur Série 2668 CR', '2668 CR Series DC micromotor'),
  ('DCX — Moteur DC à balais configurable', 'DCX — Configurable brushed DC motor'),
  ('Développement et industrialisation de produits connectés', 'Connected product development and industrialization'),
  ('Disjoncteur basse tension PXR', 'PXR low-voltage circuit breaker'),
  ('Driver de grille EiceDRIVER', 'EiceDRIVER gate driver'),
  ('DRN.. — Moteur asynchrone triphasé IE3', 'DRN.. — IE3 three-phase asynchronous motor'),
  ('eAxle intégré 150kW', 'Integrated 150kW eAxle'),
  ('EC-i 40 — Moteur brushless', 'EC-i 40 — Brushless motor'),
  ('EC-max 30 — Moteur brushless', 'EC-max 30 — Brushless motor'),
  ('ECX SPEED — Moteur brushless très haute vitesse', 'ECX SPEED — Very-high-speed brushless motor'),
  ('Électronique de lanceur — Launcher Electronics Unit', 'Launcher Electronics Unit'),
  ('Électrovanne tous fluides', 'All-fluid solenoid valve'),
  ('Électrovanne type 6213', 'Type 6213 solenoid valve'),
  ('EMA — Actionneur électromécanique', 'EMA — Electromechanical actuator'),
  ('Enregistreur de données et vidéo embarqué', 'Onboard data and video recorder'),
  ('EPC-1010 — Carte de traitement embarqué', 'EPC-1010 — Embedded processing board'),
  ('Essais en laboratoire, inspection et certification', 'Laboratory testing, inspection and certification'),
  ('Essais et ingénierie mécanique', 'Mechanical testing and engineering'),
  ('Essais matériaux et qualification soudage', 'Materials testing and welding qualification'),
  ('Essais vibratoires et qualification DO-160/ECSS', 'Vibration testing and DO-160/ECSS qualification'),
  ('Essais vibratoires multi-secteurs', 'Multi-sector vibration testing'),
  ('Essais, qualification et assurance qualité industrielle', 'Industrial testing, qualification and quality assurance'),
  ('Étude électronique de puissance sur mesure', 'Custom power electronics design'),
  ('EWC31-NG — Émetteur-récepteur bande S', 'EWC31-NG — S-band transceiver'),
  ('Fabrication de cartes et équipements électroniques (EMS)', 'Electronic board and equipment manufacturing (EMS)'),
  ('Fabrication de faisceaux électriques en série', 'Series wiring harness manufacturing'),
  ('Fabrication de faisceaux et interconnexion aéronautique', 'Aeronautical harness and interconnection manufacturing'),
  ('Fabrication de pièces mécaniques de précision', 'Precision mechanical parts manufacturing'),
  ('Faisceaux électriques et coffrets sur mesure', 'Custom wiring harnesses and enclosures'),
  ('Faisceaux et câblage sur mesure', 'Custom harnesses and wiring'),
  ('FG-1 — Frame Grabber embarqué', 'FG-1 — Onboard Frame Grabber'),
  ('FireFrame-1 — Enregistreur vidéo embarqué', 'FireFrame-1 — Onboard video recorder'),
  ('Flightkit — logiciel de vol modulaire', 'Flightkit — modular flight software'),
  ('g500 + m500 — Moteur-réducteur triphasé IE3', 'g500 + m500 — IE3 three-phase geared motor'),
  ('g500-B + MF — Moteur-réducteur conique compact', 'g500-B + MF — Compact bevel geared motor'),
  ('Générateur de puissance avionique', 'Avionics power generator'),
  ('Genteq ECM — Moteur CVC à commutation électronique', 'Genteq ECM — Electronically commutated HVAC motor'),
  ('Harnais de câblage automobile & VE', 'Automotive & EV wiring harness'),
  ('Harnais de câblage avionique', 'Avionics wiring harness'),
  ('Harnais de câblage industriel et défense', 'Industrial and defense wiring harness'),
  ('Harnais de câblage militaire haute fiabilité', 'High-reliability military wiring harness'),
  ('Harnais de câblage sur mesure', 'Custom wiring harness'),
  ('Harnais de câblage sur mesure — spatial & lanceurs', 'Custom wiring harness — space & launchers'),
  ('HeiMotion HMP — Servomoteur brushless', 'HeiMotion HMP — Brushless servomotor'),
  ('Helical — Antenne déployable', 'Helical — Deployable antenna'),
  ('HPOA — Amplificateur optique haute puissance', 'HPOA — High-power optical amplifier'),
  ('HVP800 — Connecteur HV 250A', 'HVP800 — 250A HV connector'),
  ('Imprimante 3D béton', 'Concrete 3D printer'),
  ('IMU-P4 (Unité de mesure inertielle)', 'IMU-P4 (Inertial measurement unit)'),
  ('IndraDyn A (MAD/MAF) — Servomoteurs asynchrones', 'IndraDyn A (MAD/MAF) — Asynchronous servomotors'),
  ('IndraDyn L (MLP) — Moteurs linéaires', 'IndraDyn L (MLP) — Linear motors'),
  ('IndraDyn S MSK101 — Servomoteur synchrone', 'IndraDyn S MSK101 — Synchronous servomotor'),
  ('IndraDyn T (MRT) — Moteurs-couple', 'IndraDyn T (MRT) — Torque motors'),
  ('Ingénierie de projets énergie et infrastructures critiques', 'Energy and critical infrastructure project engineering'),
  ('Ingénierie et assistance technique IT/industrie', 'IT/industrial engineering and technical assistance'),
  ('Ingénierie et assistance technique multi-sectorielle', 'Multi-sector engineering and technical assistance'),
  ('Ingénierie et automatisme industriel', 'Industrial engineering and automation'),
  ('Ingénierie nucléaire et énergie', 'Nuclear and energy engineering'),
  ('Ingénierie produit et assistance technique en régie', 'Product engineering and time-and-materials technical assistance'),
  ('Ingénierie système et modélisation', 'Systems engineering and modeling'),
  ('Inspection, essais et certification', 'Inspection, testing and certification'),
  ('Instrument Control Unit — Unité de contrôle instrument', 'Instrument Control Unit'),
  ('Intégration de lignes de production industrielles', 'Industrial production line integration'),
  ('Intégration de systèmes de levage et manutention', 'Lifting and handling system integration'),
  ('Intensium Max — ESS conteneurisé', 'Intensium Max — Containerized ESS'),
  ('Intérim et recrutement ingénierie', 'Engineering temporary staffing and recruitment'),
  ('Intérim et recrutement ingénierie/technique', 'Engineering/technical temporary staffing and recruitment'),
  ('Intérim et recrutement technique', 'Technical temporary staffing and recruitment'),
  ('Intérim et recrutement technique multi-secteurs', 'Multi-sector technical temporary staffing and recruitment'),
  ('Intérim et régie ingénierie industrielle', 'Industrial engineering temporary staffing and time-and-materials'),
  ('Interrupteurs & relais électromécaniques', 'Electromechanical switches & relays'),
  ('IQ3 Actionneur Électrique', 'IQ3 Electric Actuator'),
  ('JPSS-2 Battery — 7,9 kWh / 29,6V', 'JPSS-2 Battery — 7.9 kWh / 29.6V'),
  ('KBM — Moteur-couple sans carcasse', 'KBM — Frameless torque motor'),
  ('Kit connecteurs RF durcis RFK-12', 'RFK-12 ruggedized RF connector kit'),
  ('Lithiumate — Système de gestion de batterie', 'Lithiumate — Battery management system'),
  ('Longbow (plateforme YAM)', 'Longbow (YAM platform)'),
  ('Loop Heat Pipes (LHP) spatiaux', 'Space Loop Heat Pipes (LHP)'),
  ('LSE112 — Cellule Li-ion Spatiale', 'LSE112 — Space Li-ion cell'),
  ('LSE134 Gen III — Cellule Li-ion Spatiale', 'LSE134 Gen III — Space Li-ion cell'),
  ('M12P — Plateforme CubeSat 12U', 'M12P — 12U CubeSat platform'),
  ('M6P — Plateforme CubeSat 6U', 'M6P — 6U CubeSat platform'),
  ('Marathon Motors — Moteur AC usage général', 'Marathon Motors — General-purpose AC motor'),
  ('MCS — Servomoteur synchrone', 'MCS — Synchronous servomotor'),
  ('MGSE — Équipements de support sol pour intégration satellite', 'MGSE — Ground support equipment for satellite integration'),
  ('MicroST — Star Tracker nanosatellites', 'MicroST — Nanosatellite Star Tracker'),
  ('MIL-DTL-38999 Série III', 'MIL-DTL-38999 Series III'),
  ('MMA — Micro Horloge Atomique', 'MMA — Micro Atomic Clock'),
  ('Modem SATCOM compact CSM-200', 'CSM-200 compact SATCOM modem'),
  ('Module AC/DC pour bornes de recharge rapide (EVSE)', 'AC/DC module for fast-charging stations (EVSE)'),
  ('Module batterie haute puissance', 'High-power battery module'),
  ('Module batterie pour rover', 'Rover battery module'),
  ('Module émetteur-récepteur RF TRX-200', 'TRX-200 RF transceiver module'),
  ('Moduloo 3D — Sur-mesure', 'Moduloo 3D — Custom'),
  ('Moniteur batterie BMV-712', 'BMV-712 battery monitor'),
  ('Moteur de traction synchrone', 'Synchronous traction motor'),
  ('Moteur électrique à bobinage imprimé 3D', '3D-printed winding electric motor'),
  ('Moteur électrique industriel sur mesure', 'Custom industrial electric motor'),
  ('Moteur HXR haute tension', 'HXR high-voltage motor'),
  ('Moteur immergé à aimants permanents 4"/8"/10"', 'Permanent-magnet submersible motor 4"/8"/10"'),
  ('Moteur immergé encapsulé 4"/6"/8"', 'Encapsulated submersible motor 4"/6"/8"'),
  ('Moteur immergé rebobinable 6"-12"', 'Rewindable submersible motor 6"-12"'),
  ('Moteur immergé rebobinable à bain d''huile 4"', 'Oil-bath rewindable submersible motor 4"'),
  ('Moteur pas-à-pas hybride Série 6600 (NEMA 23)', '6600 Series hybrid stepper motor (NEMA 23)'),
  ('Moteur SIMOTICS GP', 'SIMOTICS GP motor'),
  ('MOVIGEAR® performance — Unité d''entraînement mécatronique', 'MOVIGEAR® performance — Mechatronic drive unit'),
  ('MOVIMOT® flexible — Moteur-réducteur à variateur intégré', 'MOVIMOT® flexible — Geared motor with integrated inverter'),
  ('MP 176065 — Li-ion Spatial', 'MP 176065 — Space Li-ion'),
  ('MTi — centrale inertielle (IMU)', 'MTi — inertial measurement unit (IMU)'),
  ('Nano-TTC — Sous-système TT&C CubeSat', 'Nano-TTC — CubeSat TT&C subsystem'),
  ('NANO-X — Émetteur X-band CubeSat (PC-104)', 'NANO-X — CubeSat X-band transmitter (PC-104)'),
  ('NANOBOOM — Mât déployable', 'NANOBOOM — Deployable mast'),
  ('Nanosatellite Kinéis', 'Kinéis nanosatellite'),
  ('Nœud de connectivité IIoT longue portée', 'Long-range IIoT connectivity node'),
  ('NUV300 — BMS basse tension', 'NUV300 — Low-voltage BMS'),
  ('OBC 22 kW Bidirectionnel V2G', '22 kW Bidirectional V2G OBC'),
  ('OBC-64 — Calculateur HPSC RISC-V (26 000 DMIPS)', 'OBC-64 — HPSC RISC-V computer (26,000 DMIPS)'),
  ('OBC-Cube-104 — Calculateur PC/104 CubeSat', 'OBC-Cube-104 — PC/104 CubeSat computer'),
  ('OBC-Hyper Polar — OBC CubeSat & Lanceur (AI/ML)', 'OBC-Hyper Polar — CubeSat & Launcher OBC (AI/ML)'),
  ('OBC-Johnston — Calculateur embarqué avancé', 'OBC-Johnston — Advanced onboard computer'),
  ('OBC-Polar — Calculateur CubeSat PolarFire SoC', 'OBC-Polar — PolarFire SoC CubeSat computer'),
  ('OBC-PRO2 — Calculateur professionnel 2ème génération', 'OBC-PRO2 — 2nd-generation professional computer'),
  ('OBC1 — Calculateur embarqué baseline', 'OBC1 — Baseline onboard computer'),
  ('OBC1 Supervisor — Carte de supervision', 'OBC1 Supervisor — Supervision board'),
  ('OBCM — Module OBC ultra-compact', 'OBCM — Ultra-compact OBC module'),
  ('Onduleur et chargeur DC-DC', 'Inverter and DC-DC charger'),
  ('Onduleur et filtre actif industriel', 'Industrial inverter and active filter'),
  ('Onduleur Galaxy VS 100kVA', 'Galaxy VS 100kVA UPS'),
  ('Onduleur industriel sur mesure', 'Custom industrial inverter'),
  ('Onduleur locomotive', 'Locomotive inverter'),
  ('Onduleur modulaire ONS', 'ONS modular inverter'),
  ('Onduleur solaire M70A', 'M70A solar inverter'),
  ('Orion BMS 2 — Système de gestion de batterie', 'Orion BMS 2 — Battery management system'),
  ('Pack batterie B2B sur-mesure NMC', 'Custom B2B NMC battery pack'),
  ('Pack batterie haute performance', 'High-performance battery pack'),
  ('Pack LFP 48V 100Ah connecté (IoT)', 'Connected (IoT) 48V 100Ah LFP pack'),
  ('Pack LFP stationnaire sur-mesure', 'Custom stationary LFP pack'),
  ('Pack pouch RESU ESS 10 kWh', 'RESU ESS 10 kWh pouch pack'),
  ('Pack VE 75 kWh bas-carbone', 'Low-carbon 75 kWh EV pack'),
  ('Panneau solaire déployable Sparkwing', 'Sparkwing deployable solar panel'),
  ('Payload Process-1 — Unité de traitement payload', 'Payload Process-1 — Payload processing unit'),
  ('PCDU Omni-P — Power Conditioning & Distribution (1–1500 W)', 'PCDU Omni-P — Power Conditioning & Distribution (1–1,500 W)'),
  ('PDU APC rack intelligent', 'APC intelligent rack PDU'),
  ('PF-VPX OBC — Calculateur 3U SpaceVPX PolarFire', 'PF-VPX OBC — 3U SpaceVPX PolarFire computer'),
  ('Pièces aéronautiques certifiées (MRO)', 'Certified aircraft parts (MRO)'),
  ('Plateforme satellite modulaire AFR (Azista First Runner)', 'AFR modular satellite platform (Azista First Runner)'),
  ('Plateforme STLA Medium', 'STLA Medium platform'),
  ('Polar Edge – High End — Super-calculateur IA CubeSat', 'Polar Edge – High End — CubeSat AI supercomputer'),
  ('PolarComm-Switch — Switch SpaceWire embarqué', 'PolarComm-Switch — Onboard SpaceWire switch'),
  ('PolarStore-2N — Stockage SpaceVPX 2 slots NVMe', 'PolarStore-2N — SpaceVPX storage, 2 NVMe slots'),
  ('PolarStore-2S — Stockage SpaceVPX 2 slots SSD', 'PolarStore-2S — SpaceVPX storage, 2 SSD slots'),
  ('PolarStore-4N — Stockage SpaceVPX 4 slots NVMe', 'PolarStore-4N — SpaceVPX storage, 4 NVMe slots'),
  ('PolarStore-4S — Stockage SpaceVPX 4 slots SSD', 'PolarStore-4S — SpaceVPX storage, 4 SSD slots'),
  ('Pompe centrifuge Durco Mark 3', 'Durco Mark 3 centrifugal pump'),
  ('Positionneur d''antenne 2 axes ATP-300', 'ATP-300 2-axis antenna positioner'),
  ('Positionneur numérique FIELDVUE DVC6200', 'FIELDVUE DVC6200 digital positioner'),
  ('PowerCore — système de stockage batterie', 'PowerCore — battery storage system'),
  ('PPU — Power Processing Unit (propulsion électrique)', 'PPU — Power Processing Unit (electric propulsion)'),
  ('Procédé de biorecyclage PET', 'PET biorecycling process'),
  ('Propulseur électrique spatial', 'Space electric thruster'),
  ('PSU-Polar-3U — Alimentation SpaceVPX 3U', 'PSU-Polar-3U — 3U SpaceVPX power supply'),
  ('Pulse Pack — Camion électrique', 'Pulse Pack — Electric truck'),
  ('QB056 — Servomoteur brushless 8 pôles', 'QB056 — 8-pole brushless servomotor'),
  ('Quantum Pack — Marine hybride', 'Quantum Pack — Hybrid marine'),
  ('Quantum QB — Servomoteur brushless NEMA', 'Quantum QB — NEMA brushless servomotor'),
  ('Radio tactique multibande RT-9000', 'RT-9000 multi-band tactical radio'),
  ('Radio tactique vétronique AN/PRC-200', 'AN/PRC-200 vehicle tactical radio'),
  ('RavenEye-3U-HSV-L (VNIR) — Caméra hyperspectrale grand champ', 'RavenEye-3U-HSV-L (VNIR) — Wide-field hyperspectral camera'),
  ('RavenEye-3U-HSV-S (VNIR) — Caméra hyperspectrale compact', 'RavenEye-3U-HSV-S (VNIR) — Compact hyperspectral camera'),
  ('RavenEye-3U-MSS (SWIR) — Caméra multi-spectrale infrarouge', 'RavenEye-3U-MSS (SWIR) — Infrared multispectral camera'),
  ('REC Q BMS 16S — Système de gestion de batterie', 'REC Q BMS 16S — Battery management system'),
  ('Récepteur GNSS militaire GR-Defense', 'GR-Defense military GNSS receiver'),
  ('Réducteur manuel série GD', 'GD series manual gear operator'),
  ('Régulateur MPPT SmartSolar 250/100', 'SmartSolar 250/100 MPPT controller'),
  ('Relais haute tension HVR300', 'HVR300 high-voltage relay'),
  ('Revêtements optiques de protection', 'Protective optical coatings'),
  ('Robot industriel IRB 6700', 'IRB 6700 industrial robot'),
  ('Roue de réaction agile — Reaction Wheel', 'Agile Reaction Wheel'),
  ('Roue de réaction CW0500', 'CW0500 reaction wheel'),
  ('Roue de réaction RW40', 'RW40 reaction wheel'),
  ('SADM — Mécanisme d''entraînement panneaux solaires', 'SADM — Solar array drive mechanism'),
  ('SADM — Mécanisme d''orientation de panneaux solaires', 'SADM — Solar array orientation mechanism'),
  ('Satellite E-Space (constellation propre)', 'E-Space satellite (own constellation)'),
  ('Satellite OBC & Système C&DH', 'Satellite OBC & C&DH System'),
  ('SECC — Contrôleur de communication pour charge DC', 'SECC — DC charging communication controller'),
  ('Série AM — Moteur pas-à-pas', 'AM Series — Stepper motor'),
  ('Série LM — Moteur linéaire DC', 'LM Series — DC linear motor'),
  ('Servomoteur haute dynamique', 'High-dynamic servomotor'),
  ('Servomoteur PMSM industriel', 'Industrial PMSM servomotor'),
  ('Servovanne hydraulique SV-900', 'SV-900 hydraulic servo valve'),
  ('Site de production d''hydrogène vert', 'Green hydrogen production site'),
  ('Smart Motor System — Moteur à réluctance commutée', 'Smart Motor System — Switched reluctance motor'),
  ('Solution d''automatisation et capteurs industriels', 'Industrial automation and sensor solution'),
  ('Space Solar Array — Panneau solaire spatial complet', 'Space Solar Array — Complete space solar panel'),
  ('SpaceUM-Polar — Module utilitaire SpaceVPX', 'SpaceUM-Polar — SpaceVPX utility module'),
  ('SpaceVPX-BP-DS — Backplane SpaceVPX double-slot', 'SpaceVPX-BP-DS — Double-slot SpaceVPX backplane'),
  ('SpaceVPX-BP-SS — Backplane SpaceVPX simple-slot', 'SpaceVPX-BP-SS — Single-slot SpaceVPX backplane'),
  ('SpaceWire — Module réseau SpaceWire', 'SpaceWire — SpaceWire network module'),
  ('SPARTA-G70 — Plateforme microsatellite avancée', 'SPARTA-G70 — Advanced microsatellite platform'),
  ('SPECTRA-L40 — Plateforme nanosatellite', 'SPECTRA-L40 — Nanosatellite platform'),
  ('SPRINT-L60 — Plateforme microsatellite', 'SPRINT-L60 — Microsatellite platform'),
  ('STELLAR-BATT — Batterie constellation LEO', 'STELLAR-BATT — LEO constellation battery'),
  ('Station sol robotisée', 'Robotic ground station'),
  ('Structures satellites & coiffes lanceurs', 'Satellite structures & launcher fairings'),
  ('SubConn Circular — 6, 8 et 10 contacts', 'SubConn Circular — 6, 8 and 10 contacts'),
  ('SubConn Power Battery — 2, 3 et 4 contacts', 'SubConn Power Battery — 2, 3 and 4 contacts'),
  ('Suite GNC (ADCS Complet)', 'GNC Suite (Complete ADCS)'),
  ('Supercondensateur graphène courbé', 'Curved-graphene supercapacitor'),
  ('Système de navigation GPS/INS HG-9900', 'HG-9900 GPS/INS navigation system'),
  ('Système de stockage d''énergie industriel', 'Industrial energy storage system'),
  ('Système de stockage et infrastructure e-mobilité', 'Storage system and e-mobility infrastructure'),
  ('Systèmes électroniques critiques et intégration', 'Critical electronic systems and integration'),
  ('TartanComm-Bridge — Passerelle de communication multi-protocoles', 'TartanComm-Bridge — Multi-protocol communication gateway'),
  ('TCU-L — Unité de contrôle thermique compacte', 'TCU-L — Compact thermal control unit'),
  ('TCU1 — Unité de contrôle thermique (110 capteurs / 50 actionneurs)', 'TCU1 — Thermal control unit (110 sensors / 50 actuators)'),
  ('Terminal de communication laser inter-satellite', 'Inter-satellite laser communication terminal'),
  ('TPM+ dynamic — Actionneur servo rotatif', 'TPM+ dynamic — Rotary servo actuator'),
  ('TPM+ high torque — Actionneur charges lourdes', 'TPM+ high torque — Heavy-load actuator'),
  ('Typhoon Edge — Super-calculateur IA ultime (Jetson AGX Orin 64 GB)', 'Typhoon Edge — Ultimate AI supercomputer (Jetson AGX Orin 64 GB)'),
  ('UGTS — Unité de Gestion et de Traitement Scientifique', 'UGTS — Scientific Management and Processing Unit'),
  ('Unité de distribution de puissance véhicule électrique', 'Electric vehicle power distribution unit'),
  ('Usinage de pièces structurales aéronautiques', 'Aeronautical structural parts machining'),
  ('Usinage de précision 5 axes', '5-axis precision machining'),
  ('Usinage de précision et assemblage aéronautique', 'Aeronautical precision machining and assembly'),
  ('Valeo BISG — Démarreur-générateur intégré 48V', 'Valeo BISG — 48V integrated starter-generator'),
  ('Vanne à bille Worcester série 44', 'Worcester 44 series ball valve'),
  ('Vanne à tournant sphérique inox', 'Stainless-steel ball valve'),
  ('Vanne de contrôle Fisher easy-e', 'Fisher easy-e control valve'),
  ('Vanne de propulsion satellite', 'Satellite propulsion valve'),
  ('Vanne hydraulique mobile PVG', 'PVG mobile hydraulic valve'),
  ('Vanne proportionnelle D1FP', 'D1FP proportional valve'),
  ('Vanne revêtue anticorrosion', 'Corrosion-resistant lined valve'),
  ('Variateur SINAMICS G120X', 'SINAMICS G120X drive'),
  ('Variateur VACON 100', 'VACON 100 drive'),
  ('Vérin hydraulique de stabilisation HC-450', 'HC-450 hydraulic stabilization cylinder'),
  ('Vérin hydraulique série 2H', '2H series hydraulic cylinder'),
  ('VILSA — Radio logicielle (SDR)', 'VILSA — Software-defined radio (SDR)'),
  ('VILSA XDL — Émetteur liaison descendante bande X', 'VILSA XDL — X-band downlink transmitter'),
  ('VL 45E — Li-ion Aviation', 'VL 45E — Aviation Li-ion'),
  ('Wrapped Rib — Réflecteur déployable', 'Wrapped Rib — Deployable reflector'),
  ('XRI Severe Duty — Moteur triphasé IEEE841', 'XRI Severe Duty — IEEE841 three-phase motor'),
  ('Module Bluestorage 35 kWh', 'Bluestorage 35 kWh module'),
  ('Module ESS PRiMX 50kWh', 'PRiMX 50kWh ESS module'),
  ('Module IGBT EasyPACK', 'EasyPACK IGBT module')
) AS v(fr, en)
WHERE p.name = v.fr
  AND p.name_en IS NULL;

-- Contrôle 1 : la vue expose bien name_en (doit renvoyer 1 ligne).
SELECT column_name FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'v_products_full' AND column_name = 'name_en';

-- Contrôle 2 : produits avec un nom anglais / total.
SELECT count(*) FILTER (WHERE name_en IS NOT NULL) AS noms_traduits, count(*) AS total_produits FROM public.products;
