-- ============================================================
-- Traduction anglaise des VALEURS de caractéristiques (product_specs.value_en)
-- 2026-10 — 834 valeurs FR -> EN, appliquées à toutes les lignes dont
-- la valeur correspond et qui n'ont pas encore de value_en.
--
-- Les valeurs purement numériques ou déjà en anglais (« 28 V », « PCIe Gen3 »,
-- « X-band ») ne sont pas touchées : le site retombe sur la valeur d'origine.
-- Sûr à relancer : ne remplit que les lignes où value_en IS NULL.
-- ============================================================

UPDATE product_specs AS s
SET value_en = v.en
FROM (VALUES
  ('Sur mesure', 'Custom'),
  ('Observation de la Terre (imagerie haute resolution)', 'Earth observation (high-resolution imaging)'),
  ('5 ans en LEO', '5 years in LEO'),
  ('3.3 à 16 V', '3.3 to 16 V'),
  ('20 à 30 krad', '20 to 30 krad'),
  ('2.5 à 40 mW', '2.5 to 40 mW'),
  ('PCDU miniaturisée', 'Miniaturized PCDU'),
  ('Jusqu''à 3 500 kW', 'Up to 3,500 kW'),
  ('Jusqu''à 300 kg', 'Up to 300 kg'),
  ('RS485 et IP distant', 'RS485 and remote IP'),
  ('Datasheet PDF disponible sur demande via le formulaire ACTIA SatCom', 'PDF datasheet available on request via the ACTIA SatCom form'),
  ('100W ou 150W', '100W or 150W'),
  ('SSPA extérieur', 'Outdoor SSPA'),
  ('RS485 et Ethernet IP', 'RS485 and Ethernet IP'),
  ('Liquide haute performance', 'High-performance liquid'),
  ('Préamplificateur/convertisseur redondants, alimentation 3+1', 'Redundant preamplifier/converter, 3+1 power supply'),
  ('2 interfaces de supervision et contrôle', '2 supervision and control interfaces'),
  ('Contrôleur de commutation 1+1', '1+1 switchover controller'),
  ('Stations sol fixes ou transportables', 'Fixed or transportable ground stations'),
  ('Redondance 1+1 ou 2+1', '1+1 or 2+1 redundancy'),
  ('Air ou liquide', 'Air or liquid'),
  ('Interface web avancée pour contrôle distant', 'Advanced web interface for remote control'),
  ('Linéariseur intégré (version -LIN)', 'Integrated linearizer (-LIN version)'),
  ('Linéariseur intégral, contrôleur de commutation 2+1', 'Integral linearizer, 2+1 switchover controller'),
  ('Ku-band (jusqu''à 14.8 GHz)', 'Ku-band (up to 14.8 GHz)'),
  ('Contrôleur 1+1 intégré', 'Integrated 1+1 controller'),
  ('Air, moteur brushless haute fiabilité', 'Air, high-reliability brushless motor'),
  ('Linéariseur intégral, convertisseur bande L', 'Integral linearizer, L-band converter'),
  ('-40°C à +50°C', '-40°C to +50°C'),
  ('Jusqu''à 90W AC', 'Up to 90W AC'),
  ('26 à 42 VDC', '26 to 42 VDC'),
  ('Carte de format carte de crédit', 'Credit-card-format board'),
  ('3 connecteurs haute densité, montage sur carte mère', '3 high-density connectors, motherboard mounting'),
  ('256 canaux d''énergie, forme d''onde numérisée', '256 energy channels, digitized waveform'),
  ('Protons 13-200 MeV, électrons 350 keV-3 MeV', 'Protons 13-200 MeV, electrons 350 keV-3 MeV'),
  ('Contrôle thermique, distribution de puissance', 'Thermal control, power distribution'),
  ('Jusqu''à 6 SpaceWire, LVDS, RS422', 'Up to 6 SpaceWire, LVDS, RS422'),
  ('8 Gbps (4 Gbps entrée, 4 Gbps sortie)', '8 Gbps (4 Gbps input, 4 Gbps output)'),
  ('ECSS classe 2 ou 3', 'ECSS class 2 or 3'),
  ('Non régulé, 20-40V', 'Unregulated, 20-40V'),
  ('Unité de supervision et reconfiguration tolérante aux radiations', 'Radiation-tolerant supervision and reconfiguration unit'),
  ('Convertisseurs DC/DC, module processeur, traitement numérique FPGA', 'DC/DC converters, processor module, FPGA digital processing'),
  ('Distribution de puissance intégrée', 'Integrated power distribution'),
  ('1 carte CPU principale + 1 carte d''interface personnalisable', '1 main CPU board + 1 customizable interface board'),
  ('Zynq 7030 ou 7045, 1GB DDR3 (512MB avec protection ECC)', 'Zynq 7030 or 7045, 1GB DDR3 (512MB with ECC protection)'),
  ('Fond de panier standard PC104', 'Standard PC104 backplane'),
  ('RS422, LVDS/SpW, entrées analogiques, thermistances, sorties PWM, pont en H, distribution de puissance', 'RS422, LVDS/SpW, analog inputs, thermistors, PWM outputs, H-bridge, power distribution'),
  ('16MB QSPI (boot), 1GB NVM, 32GB mémoire de masse, 256kB FRAM', '16MB QSPI (boot), 1GB NVM, 32GB mass memory, 256kB FRAM'),
  ('2 Tbits (1 module), évolutif jusqu''à 8 Tbits (4 modules)', '2 Tbits (1 module), scalable up to 8 Tbits (4 modules)'),
  ('1GB DDR3 (512MB avec ECC)', '1GB DDR3 (512MB with ECC)'),
  ('CAN / UART, mono ou double antenne', 'CAN / UART, single or dual antenna'),
  ('Jusqu''à 1 m', 'Up to 1 m'),
  ('Jusqu''à 20 mm/s', 'Up to 20 mm/s'),
  ('Microservices, clusterisée, prête pour le cloud', 'Microservices, clustered, cloud-ready'),
  ('Web moderne, responsive, tableaux de bord personnalisables', 'Modern responsive web, customizable dashboards'),
  ('Intérim, CDD, CDI', 'Temporary, fixed-term, permanent'),
  ('Bobinage imprimé 3D', '3D-printed winding'),
  ('1 ou 2 x 500 W (fibre Yb)', '1 or 2 x 500 W (Yb fiber)'),
  ('> 100 millions d''heures en orbite (toutes générations CCHP)', '> 100 million hours in orbit (all CCHP generations)'),
  ('Enveloppe aluminium extrudé, ammoniac anhydre', 'Extruded aluminum envelope, anhydrous ammonia'),
  ('20 à 50 W', '20 to 50 W'),
  ('22 à 38 V (5V secondaire)', '22 to 38 V (5V secondary)'),
  ('Li-ion COTS qualifié spatial', 'Space-qualified COTS Li-ion'),
  ('Jusqu''à 12,5 ans', 'Up to 12.5 years'),
  ('Interne ou externe', 'Internal or external'),
  ('> 290 unités en orbite, 2,5 M heures de fonctionnement', '> 290 units in orbit, 2.5 M operating hours'),
  ('-40°C à +90°C', '-40°C to +90°C'),
  ('3°/s en < 2 s', '3°/s in < 2 s'),
  ('10 ans en LEO', '10 years in LEO'),
  ('Jusqu''a 3 tonnes', 'Up to 3 tonnes'),
  ('GEO / MEO Télécom & Nav', 'GEO / MEO Telecom & Nav'),
  ('S : 150-262 Ah · M : 306-575 Ah · L : 612-805 Ah', 'S: 150-262 Ah · M: 306-575 Ah · L: 612-805 Ah'),
  ('Passif, sans alimentation', 'Passive, unpowered'),
  ('Frein à induction magnétique passif', 'Passive magnetic induction brake'),
  ('Retrait actif de debris (mitigation fin de vie)', 'Active debris removal (end-of-life mitigation)'),
  ('Distribution puissance + séquencement', 'Power distribution + sequencing'),
  ('Intégrée', 'Integrated'),
  ('3 à 6,8 tonnes', '3 to 6.8 tonnes'),
  ('7 à 24 kW (evolutif)', '7 to 24 kW (scalable)'),
  ('Modulaire', 'Modular'),
  ('Modulaire, compacte', 'Modular, compact'),
  ('Etat de l''art', 'State of the art'),
  ('> 10 ans en orbite', '> 10 years in orbit'),
  ('Jusqu''a 75 N.m.s', 'Up to 75 N.m.s'),
  ('Couverture/capacite/frequence ajustables en orbite', 'Coverage/capacity/frequency adjustable in orbit'),
  ('Jusqu''à 2 kW', 'Up to 2 kW'),
  ('MDA AURORA (> 200 unités)', 'MDA AURORA (> 200 units)'),
  ('Panneau déployable rigide', 'Rigid deployable panel'),
  ('28 – 100 V DC régulé', '28 – 100 V DC regulated'),
  ('Jusqu''à 20 kW', 'Up to 20 kW'),
  ('Architecture redondante', 'Redundant architecture'),
  ('MPPT + régulation shunt', 'MPPT + shunt regulation'),
  ('Jusqu''à 400 V', 'Up to 400 V'),
  ('Jusqu''a 23 kW', 'Up to 23 kW'),
  ('Jusqu''a 1,5 kW', 'Up to 1.5 kW'),
  ('22-38 V (non regulee)', '22-38 V (unregulated)'),
  ('22-38V non régulée, jusqu''à 1,5 kW', '22-38V unregulated, up to 1.5 kW'),
  ('Jusqu''à 0,5 N·m', 'Up to 0.5 N·m'),
  ('Jusqu''à 50 N·m·s', 'Up to 50 N·m·s'),
  ('Roue de réaction', 'Reaction wheel'),
  ('> 15 ans en orbite', '> 15 years in orbit'),
  ('Jusqu''à 25 kW', 'Up to 25 kW'),
  ('Constellations LEO (mégaconstellations)', 'LEO constellations (mega-constellations)'),
  ('Jusqu''à 7 ans', 'Up to 7 years'),
  ('Standardisée, cadence élevée', 'Standardized, high production rate'),
  ('Jusqu''à 10 Gbps', 'Up to 10 Gbps'),
  ('Régie ou forfait', 'Time-and-materials or fixed price'),
  ('Industrie, énergie, défense, aéro', 'Industry, energy, defense, aerospace'),
  ('0,12 – 14,4 Nm selon taille', '0.12 – 14.4 Nm depending on size'),
  ('Supérieure à 20 000 heures', 'Over 20,000 hours'),
  ('5 tailles métriques', '5 metric sizes'),
  ('Jusqu''à 160 jours', 'Up to 160 days'),
  ('Jusqu''à 3 200 km', 'Up to 3,200 km'),
  ('Jusqu''à 1 200 kW', 'Up to 1,200 kW'),
  ('Élevé basse vitesse', 'High at low speed'),
  ('Jusqu''à 500 kW', 'Up to 500 kW'),
  ('Air forcé', 'Forced air'),
  ('65 dB minimum à 10 GHz', '65 dB minimum at 10 GHz'),
  ('-65 à +200 °C', '-65 to +200 °C'),
  ('LHCP et RHCP simultanées, connecteurs séparés', 'Simultaneous LHCP and RHCP, separate connectors'),
  ('Jusqu''a 94 kg', 'Up to 94 kg'),
  ('TID ≥ 100 krad(Si), SEL immune jusqu''à 80 MeV·cm²/mg', 'TID ≥ 100 krad(Si), SEL immune up to 80 MeV·cm²/mg'),
  ('Microsatellite (jusqu''a 130 kg hors charge utile)', 'Microsatellite (up to 130 kg excluding payload)'),
  ('Jusqu''a 170 kg (charge utile incluse)', 'Up to 170 kg (payload included)'),
  ('1 W à 1200 W', '1 W to 1,200 W'),
  ('-160 °C à +120 °C', '-160 °C to +120 °C'),
  ('Boucle à pompage capillaire (transfert diphasique passif)', 'Capillary-pumped loop (passive two-phase transfer)'),
  ('Rendez-vous et capture magnetique', 'Rendezvous and magnetic capture'),
  ('Operations de rendez-vous reussies en mai 2022', 'Rendezvous operations successfully completed in May 2022'),
  ('Sans changement de layout entrepôt', 'No warehouse layout change'),
  ('CAN, UART, GPS, 4G selon configuration', 'CAN, UART, GPS, 4G depending on configuration'),
  ('20 ans+ (fabrication française)', '20+ years (French manufacturing)'),
  ('Jusqu''à 114°', 'Up to 114°'),
  ('114° par capteur (2 unités nécessaires pour couverture 4π)', '114° per sensor (2 units needed for 4π coverage)'),
  ('102 g (avec 3 capteurs)', '102 g (with 3 sensors)'),
  ('Jusqu''a 100 Mbps', 'Up to 100 Mbps'),
  ('Jusqu''a 30 kg', 'Up to 30 kg'),
  ('1 To par unite de traitement de donnees', '1 TB per data processing unit'),
  ('Slip ring or-sur-or intégré', 'Integrated gold-on-gold slip ring'),
  ('20+ ans, 100 % succès mission', '20+ years, 100% mission success'),
  ('Microsatellite → GEO haute puissance', 'Microsatellite → high-power GEO'),
  ('Anti-microvibration disponible', 'Anti-microvibration available'),
  ('3 500+ années en orbite', '3,500+ years in orbit'),
  ('40+ ans, 100 % succès mission', '40+ years, 100% mission success'),
  ('Unitaire + série / constellation LEO', 'One-off + series / LEO constellation'),
  ('Concu pour 25 missions', 'Designed for 25 missions'),
  ('Pas de risque thermique', 'No thermal risk'),
  ('-20 à +60 °C', '-20 to +60 °C'),
  ('ATEX disponible', 'ATEX available'),
  ('0 à 500 bars', '0 to 500 bar'),
  ('Pétrochimie, chimie, pharma, agroalimentaire', 'Petrochemicals, chemicals, pharma, food processing'),
  ('-200°C à +200°C', '-200°C to +200°C'),
  ('Jusqu''a 400 kW', 'Up to 400 kW'),
  ('10 – 100 kW (jusqu''à 120 kW en pointe)', '10 – 100 kW (up to 120 kW peak)'),
  ('Air (MAD) ou liquide (MAF) selon variante', 'Air (MAD) or liquid (MAF) depending on variant'),
  ('Jusqu''à 11 000 tr/min', 'Up to 11,000 rpm'),
  ('Jusqu''à 21 500 N', 'Up to 21,500 N'),
  ('Liquide, boîtier IP65 inox', 'Liquid, IP65 stainless-steel housing'),
  ('Jusqu''à 600 m/min', 'Up to 600 m/min'),
  ('58,3 – 67,6 A selon variante', '58.3 – 67.6 A depending on variant'),
  ('Haute résolution, mono ou multitour selon variante', 'High resolution, single- or multi-turn depending on variant'),
  ('Jusqu''à 9 000 tr/min, IP65', 'Up to 9,000 rpm, IP65'),
  ('Jusqu''à 13 800 Nm', 'Up to 13,800 Nm'),
  ('Kit rotor/stator, sans réducteur', 'Rotor/stator kit, gearless'),
  ('Liquide (encapsulage thermique) ou convection naturelle', 'Liquid (thermal encapsulation) or natural convection'),
  ('PRISMA, SkySat — 46 unités', 'PRISMA, SkySat — 46 units'),
  ('128°×128° nominal, 172°×172° non-obstrué', '128°×128° nominal, 172°×172° unobstructed'),
  ('±0.2 à 1.5°', '±0.2 to 1.5°'),
  ('Capteur solaire analogique (détecteur à quadrants)', 'Analog sun sensor (quadrant detector)'),
  ('Logiciel de vol modulaire', 'Modular flight software'),
  ('Ultra-rapide (~1 min annoncée)', 'Ultra-fast (~1 min claimed)'),
  ('Tiers de confiance indépendant', 'Independent trusted third party'),
  ('0,1–600 L/min', '0.1–600 L/min'),
  ('110 - 150 kW (30-80% en 26 min)', '110 - 150 kW (30-80% in 26 min)'),
  ('Bipolaire, bidirectionnel, régénératif (4 quadrants)', 'Bipolar, bidirectional, regenerative (4 quadrants)'),
  ('Mise en forme de faisceau MPLC (22 brevets)', 'MPLC beam shaping (22 patents)'),
  ('> 90 % du PET', '> 90% of the PET'),
  ('0,5C charge/décharge', '0.5C charge/discharge'),
  ('≥ 6 000 cycles à 0,25C/0,25C', '≥ 6,000 cycles at 0.25C/0.25C'),
  ('-30 à +55 °C', '-30 to +55 °C'),
  ('Régie', 'Time-and-materials'),
  ('Sur site / cloud', 'On-site / cloud'),
  ('Temps réel', 'Real time'),
  ('Automatisée', 'Automated'),
  ('CAVUSmartTags® temps réel', 'CAVUSmartTags® real time'),
  ('Télémesure, télécommande, HK', 'Telemetry, telecommand, HK'),
  ('Max puissance par cm²', 'Max power per cm²'),
  ('Triple-jonction GaAs haute eff.', 'High-efficiency GaAs triple-junction'),
  ('Stockage masse données / vidéo', 'Mass data / video storage'),
  ('Carte de traitement embarqué', 'Embedded processing board'),
  ('RAW 12-bit Bayer, zéro-compression', '12-bit Bayer RAW, zero compression'),
  ('Hardware, temps réel, sans scaling', 'Hardware, real time, no scaling'),
  ('Caméras CAVU + interfaces standard', 'CAVU cameras + standard interfaces'),
  ('Enregistreur / Frame Grabber vidéo', 'Video recorder / Frame Grabber'),
  ('Contrôle cycle de vie instrument', 'Instrument life-cycle control'),
  ('Mise sous tension, calibration', 'Power-up, calibration'),
  ('2ème génération', '2nd generation'),
  ('3,3V / 5V / 12V régulés, 10 LCLs', '3.3V / 5V / 12V regulated, 10 LCLs'),
  ('28 V non régulé', '28 V unregulated'),
  ('CAN redondant, RS422', 'Redundant CAN, RS422'),
  ('Intégré, compatible SA CAVU', 'Integrated, compatible with CAVU solar arrays'),
  ('2× 256 GB eMMC redondants', '2× 256 GB redundant eMMC'),
  ('28V DC bus (18-36V, MIL-STD-704F) vers 5V/12V/3,3V régulés', '28V DC bus (18-36V, MIL-STD-704F) to regulated 5V/12V/3.3V'),
  ('Multi-rails régulés', 'Regulated multi-rail'),
  ('Missions scientifiques ciblées', 'Targeted scientific missions'),
  ('EO, végétation, minéralogie', 'EO, vegetation, mineralogy'),
  ('CubeSat à small satellites', 'CubeSats to small satellites'),
  ('GaAs 30 % ou 32 % TJ', 'GaAs 30% or 32% TJ'),
  ('2–400 Mbps par lien', '2–400 Mbps per link'),
  ('PWM ou linéaire', 'PWM or linear'),
  ('PWM ou linéaire (env. super-calme)', 'PWM or linear (ultra-quiet environment)'),
  ('8 entrées / 8 sorties', '8 inputs / 8 outputs'),
  ('50 canaux, jusqu''à 50 W/ch', '50 channels, up to 50 W/ch'),
  ('Multi-voies caméra + NVMe', 'Multi-lane camera + NVMe'),
  ('Aéro, spatial, auto, ferroviaire', 'Aerospace, space, automotive, rail'),
  ('Combrée (défense/nucléaire/médical), Neuilly-en-Thelle (industrie/ferroviaire/médical)', 'Combrée (defense/nuclear/medical), Neuilly-en-Thelle (industry/rail/medical)'),
  ('Liaisons de collecte (feeder links) GEO/LEO', 'GEO/LEO feeder links'),
  ('jusqu''à 5 W', 'up to 5 W'),
  ('Jusqu''à 5 W (11 W en développement)', 'Up to 5 W (11 W in development)'),
  ('Jusqu''à 2 m × 2 m', 'Up to 2 m × 2 m'),
  ('Pulvérisation magnétron', 'Magnetron sputtering'),
  ('Convection forcée', 'Forced convection'),
  ('Automatique, motorisé 2 axes', 'Automatic, motorized 2-axis'),
  ('-30 à +60 °C', '-30 to +60 °C'),
  ('Contrôleur NAND', 'NAND controller'),
  ('Ethernet 10G ou optique, 10 ports', '10G Ethernet or optical, 10 ports'),
  ('Rayonnement UHF/S-band + mécanisme de déploiement', 'UHF/S-band radiation + deployment mechanism'),
  ('25 unités livrées, constellation Kinéis (28 kg, 8 ans)', '25 units delivered, Kinéis constellation (28 kg, 8 years)'),
  ('4 brins rigides en cuivre-béryllium', '4 rigid beryllium-copper strands'),
  ('Antenne déployable', 'Deployable antenna'),
  ('Building block réutilisable', 'Reusable building block'),
  ('Mât déployable', 'Deployable mast'),
  ('8 ans en orbite', '8 years in orbit'),
  ('Seule roue nanosat qualifiée 8 ans', 'Only nanosat wheel qualified for 8 years'),
  ('France 2030 (pré-qualification)', 'France 2030 (pre-qualification)'),
  ('Mécanisme rotatif panneaux solaires', 'Solar panel rotary mechanism'),
  ('LFP sans cobalt, 0,7C continu / 1C crête (20 min)', 'Cobalt-free LFP, 0.7C continuous / 1C peak (20 min)'),
  ('Projet ou régie', 'Project or time-and-materials'),
  ('80 g (avec caméras)', '80 g (with cameras)'),
  ('Haute précision', 'High precision'),
  ('24 kRad, durée de vie 5 ans+', '24 kRad, 5+ year lifetime'),
  ('Testée (qualifiée vol)', 'Tested (flight-qualified)'),
  ('15 à 80 W', '15 to 80 W'),
  ('12 à 28 V', '12 to 28 V'),
  ('Jusqu''à 350 L/min', 'Up to 350 L/min'),
  ('Modulaires', 'Modular'),
  ('-15°C à +50°C, vent jusqu''à 35 nds', '-15°C to +50°C, wind up to 35 kn'),
  ('Contrôle de déploiement, Maximum Power Point Tracking (MPPT)', 'Deployment control, Maximum Power Point Tracking (MPPT)'),
  ('Distribution et régulation de puissance embarquée', 'Onboard power distribution and regulation'),
  ('Jusqu''à 15 ans', 'Up to 15 years'),
  ('Miniature, sans fil', 'Miniature, wireless'),
  ('868/915 MHz, portée jusqu''à 150 m en intérieur', '868/915 MHz, range up to 150 m indoors'),
  ('Température, proximité, humidité', 'Temperature, proximity, humidity'),
  ('> 15 ans en stockage', '> 15 years in storage'),
  ('Jusqu''à 6 300 A', 'Up to 6,300 A'),
  ('Jusqu''à 690 V', 'Up to 690 V'),
  ('Jusqu''à 400 km en 20 min', 'Up to 400 km in 20 min'),
  ('Jusqu''à 300 kW', 'Up to 300 kW'),
  ('Distribuée, une carte de mesure/équilibrage par cellule', 'Distributed, one measurement/balancing board per cell'),
  ('Jusqu''à 255 cellules (~900 V), 16 banques, 16 chaînes en parallèle', 'Up to 255 cells (~900 V), 16 banks, 16 parallel strings'),
  ('CAN et RS232', 'CAN and RS232'),
  ('Alimentation sans coupure + filtrage actif', 'Uninterruptible power supply + active filtering'),
  ('Électrique', 'Electric'),
  ('Plus de 150 000 unités, 1 200+ navires', 'More than 150,000 units, 1,200+ vessels'),
  ('Intégré', 'Integrated'),
  ('Jusqu''à 420 bar', 'Up to 420 bar'),
  ('Modulaire, redondante', 'Modular, redundant'),
  ('Jusqu''à 80 kVA', 'Up to 80 kVA'),
  ('Jusqu''a 1 Gbps (X/K-band)', 'Up to 1 Gbps (X/K-band)'),
  ('Jusqu''a 5 ans', 'Up to 5 years'),
  ('Jusqu''a 0,01°', 'Up to 0.01°'),
  ('Jusqu''a 4U (7,5 kg)', 'Up to 4U (7.5 kg)'),
  ('Jusqu''a 4 Gbps', 'Up to 4 Gbps'),
  ('200 - 500 m/s (selon configuration)', '200 - 500 m/s (depending on configuration)'),
  ('Récepteur GNSS intégré', 'Integrated GNSS receiver'),
  ('ARM Cortex-M7 spatialisé', 'Space-grade ARM Cortex-M7'),
  ('3-5 ans (ou illimitée en version solaire)', '3-5 years (or unlimited in solar version)'),
  ('LoRa longue portée jusqu''à 15 km', 'Long-range LoRa up to 15 km'),
  ('Jusqu''à 40 m', 'Up to 40 m'),
  ('Capteur laser sans fil', 'Wireless laser sensor'),
  ('Horloges PHARAO et SHM', 'PHARAO and SHM clocks'),
  ('Résolution des obsolescences composants', 'Component obsolescence resolution'),
  ('Durcis aux radiations', 'Radiation-hardened'),
  ('Alimentation de l''ICU', 'ICU power supply'),
  ('DC/DC isolée', 'Isolated DC/DC'),
  ('Quad-core LEON4 SPARC V8 tolérant aux fautes (ESA NGMP)', 'Fault-tolerant quad-core LEON4 SPARC V8 (ESA NGMP)'),
  ('Gestion TM/TC, calculs logiciels dédiés', 'TM/TC handling, dedicated software computations'),
  ('Génération et fourniture de puissance', 'Power generation and supply'),
  ('Électronique front-end du capteur optique', 'Optical sensor front-end electronics'),
  ('Satellites scientifiques, sondes, observation de la Terre, exploration', 'Scientific satellites, probes, Earth observation, exploration'),
  ('Modulaire (combinable avec modules CPU et FPGA)', 'Modular (can be combined with CPU and FPGA modules)'),
  ('Autonome ou intégré (Modular ICU)', 'Standalone or integrated (Modular ICU)'),
  ('Alimentation électrique complète du rover', 'Complete rover electrical power'),
  ('Modulaire, 4 modules principaux', 'Modular, 4 main modules'),
  ('CubeSat (6U à 27U)', 'CubeSat (6U to 27U)'),
  ('2 PPU vers 1 propulseur', '2 PPUs to 1 thruster'),
  ('Commutation des signaux propulseur/XFC', 'Thruster/XFC signal switching'),
  ('Alimentation/contrôle instrument, traitement scientifique', 'Instrument power/control, scientific processing'),
  ('Caméra front-end', 'Front-end camera'),
  ('Pile longue durée', 'Long-life battery'),
  ('LoRaWAN ou 4G', 'LoRaWAN or 4G'),
  ('Décret Tertiaire, ISO 50 001, IPE, Décret BACS', 'Tertiary Decree, ISO 50001, IPE, BACS Decree'),
  ('Plateforme de supervision Ewattch', 'Ewattch monitoring platform'),
  ('10 mm (75A) à 36 mm (600A)', '10 mm (75A) to 36 mm (600A)'),
  ('24 à 180 cellules (extensible jusqu''à 800 V DC via modules distants)', '24 to 180 cells (expandable up to 800 V DC via remote modules)'),
  ('0,5 à 5,0 V', '0.5 to 5.0 V'),
  ('-40°C à +80°C', '-40°C to +80°C'),
  ('Gyroscope à fibre optique (FOG)', 'Fiber-optic gyroscope (FOG)'),
  ('Jusqu''à 600 bacs/heure par poste', 'Up to 600 totes/hour per station'),
  ('Propulsion électrique', 'Electric propulsion'),
  ('Jusqu''a 400 kg', 'Up to 400 kg'),
  ('Jusqu''a 1 km/s', 'Up to 1 km/s'),
  ('Régie ou plateau d''essais', 'Time-and-materials or test platform'),
  ('Jusqu''à 18 mNm (99 mNm en version SC)', 'Up to 18 mNm (99 mNm in SC version)'),
  ('Jusqu''à 62 W (variante 3268)', 'Up to 62 W (3268 variant)'),
  ('6 – 24 V (jusqu''à 48 V selon variante)', '6 – 24 V (up to 48 V depending on variant)'),
  ('Jusqu''à 29 000 tr/min', 'Up to 29,000 rpm'),
  ('Jusqu''à 0,94 mNm', 'Up to 0.94 mNm'),
  ('Jusqu''à 16 000 tr/min', 'Up to 16,000 rpm'),
  ('Jusqu''à 4,13 mNm', 'Up to 4.13 mNm'),
  ('Jusqu''à 8 630 tr/min', 'Up to 8,630 rpm'),
  ('Jusqu''à 71,2 mNm', 'Up to 71.2 mNm'),
  ('84 W continue, 653 mNm au blocage, ~7 900 tr/min à vide', '84 W continuous, 653 mNm stall, ~7,900 rpm no-load'),
  ('Jusqu''à 7 980 tr/min', 'Up to 7,980 rpm'),
  ('7,5° à 18° selon série', '7.5° to 18° depending on series'),
  ('0,65 – 152 mNm selon taille (8 à 32 mm)', '0.65 – 152 mNm depending on size (8 to 32 mm)'),
  ('1,4 – 12 V selon modèle', '1.4 – 12 V depending on model'),
  ('15 – 220 mm selon série', '15 – 220 mm depending on series'),
  ('De 33×8 mm à 74×20 mm (L×l)', 'From 33×8 mm to 74×20 mm (L×W)'),
  ('De plusieurs millions à plusieurs centaines de millions de cycles', 'From several million to several hundred million cycles'),
  ('Jusqu''à 9,2 N (série LM 2070)', 'Up to 9.2 N (LM 2070 series)'),
  ('Projet clé en main', 'Turnkey project'),
  ('Jusqu''à 1 800 m³/h', 'Up to 1,800 m³/h'),
  ('Jusqu''à 180 m', 'Up to 180 m'),
  ('jusqu''à 27 bar', 'up to 27 bar'),
  ('-75°C à +370°C', '-75°C to +370°C'),
  ('Aimants permanents (rendement supérieur à l''asynchrone)', 'Permanent magnets (higher efficiency than induction)'),
  ('Stator hermétique, rempli d''eau, inox résistant à la corrosion', 'Hermetic stator, water-filled, corrosion-resistant stainless steel'),
  ('Monophasé 220-230 V ou triphasé 380-400 V', 'Single-phase 220-230 V or three-phase 380-400 V'),
  ('Rebobinable (vs encapsulé jetable)', 'Rewindable (vs. disposable encapsulated)'),
  ('Bain d''huile', 'Oil bath'),
  ('3 principaux + 2 auxiliaires (jusqu''à 7 sorties)', '3 main + 2 auxiliary (up to 7 outputs)'),
  ('3.3V à 52V', '3.3V to 52V'),
  ('23 lancements (21 reussis) au 01/2026', '23 launches (21 successful) as of 01/2026'),
  ('Applications sous-marines', 'Underwater applications'),
  ('Longue portée, faible latence', 'Long range, low latency'),
  ('0.17 à 0.9 W', '0.17 to 0.9 W'),
  ('3.20 à 3.40 V', '3.20 to 3.40 V'),
  ('A partir de 77 Wh', 'From 77 Wh'),
  ('Jusqu''a 9U', 'Up to 9U'),
  ('Jusqu''a 3U', 'Up to 3U'),
  ('Plus de 40 ans en fabrication de harnais de câblage', 'More than 40 years in wiring harness manufacturing'),
  ('12 pays (Europe, Asie, Amérique)', '12 countries (Europe, Asia, Americas)'),
  ('Réseau de stations partagées', 'Shared station network'),
  ('Aéro, énergie, aluminium, naval', 'Aerospace, energy, aluminum, naval'),
  ('LCO/Graphite, boîtier aluminium, fabriqué à Kyoto (Japon)', 'LCO/Graphite, aluminum housing, made in Kyoto (Japan)'),
  ('40% sur > 10 ans', '40% over > 10 years'),
  ('-20 à +30 °C', '-20 to +30 °C'),
  ('-40 à +60 °C', '-40 to +60 °C'),
  ('Fabricants de satellites et de lanceurs', 'Satellite and launch vehicle manufacturers'),
  ('Revue de conception, prototypage, production petite/grande série, tests & QA', 'Design review, prototyping, small/large series production, testing & QA'),
  ('Microsatellite avancé', 'Advanced microsatellite'),
  ('Haut de gamme Hemeria', 'Hemeria high-end'),
  ('Observation / télécommunication', 'Observation / telecommunications'),
  ('Charge utile renforcée', 'Reinforced payload'),
  ('Défense, aéronautique', 'Defense, aeronautics'),
  ('± 2 ft (basse altitude)', '± 2 ft (low altitude)'),
  ('-1 000 à 80 000 ft', '-1,000 to 80,000 ft'),
  ('0,25°/h (précision de pointe pour un IMU MEMS tactique)', '0.25°/h (peak accuracy for a tactical MEMS IMU)'),
  ('Jusqu''à 1 kHz', 'Up to 1 kHz'),
  ('-40 à +85 °C', '-40 to +85 °C'),
  ('10 min (dérive < 0,1 NM)', '10 min (drift < 0.1 NM)'),
  ('SiC MOSFET 4e gén.', '4th-gen SiC MOSFET'),
  ('-40 à +175 °C', '-40 to +175 °C'),
  ('Jusqu''à 1 700 V', 'Up to 1,700 V'),
  ('Élevée', 'High'),
  ('Jusqu''à 600 A', 'Up to 600 A'),
  ('0.094 à 0.10 kg', '0.094 to 0.10 kg'),
  ('~ 80 passages/jour sur chaque point du globe', '~80 passes/day over every point on the globe'),
  ('0,18 – 180 Nm selon taille', '0.18 – 180 Nm depending on size'),
  ('24 – 96 V DC (variante basse tension) ou 120/240/400/480 V AC', '24 – 96 V DC (low-voltage variant) or 120/240/400/480 V AC'),
  ('Jusqu''à 8 000 tr/min', 'Up to 8,000 rpm'),
  ('8 000 tr/min (taille 2-3), 6 000 tr/min (tailles 4 à 7)', '8,000 rpm (size 2-3), 6,000 rpm (sizes 4 to 7)'),
  ('EHEDG, 3-A, matériaux FDA agroalimentaire', 'EHEDG, 3-A, FDA food-grade materials'),
  ('Inox 316L (toutes surfaces exposées)', '316L stainless steel (all exposed surfaces)'),
  ('19 tailles disponibles (AKMH2x à AKMH6x)', '19 sizes available (AKMH2x to AKMH6x)'),
  ('Sans carcasse, paliers fournis par la machine hôte', 'Frameless, bearings provided by the host machine'),
  ('Bobinages, longueurs d''empilement et connexions modifiables sur mesure', 'Windings, stack lengths and connections customizable'),
  ('> 300 satellites en production', '> 300 satellites in production'),
  ('> 60 satellites lancés', '> 60 satellites launched'),
  ('Jusqu''a 100 kg', 'Up to 100 kg'),
  ('Jusqu''a 250 kg', 'Up to 250 kg'),
  ('Jusqu''a 2,5 Gbps', 'Up to 2.5 Gbps'),
  ('Magnétomètre, gyroscope', 'Magnetometer, gyroscope'),
  ('OBC ou DPU', 'OBC or DPU'),
  ('Algorithmes IA à bord', 'Onboard AI algorithms'),
  ('Baïonnette quart de tour', 'Quarter-turn bayonet'),
  ('Maillé ad-hoc', 'Ad-hoc mesh'),
  ('Jusqu''a 6 000 kg', 'Up to 6,000 kg'),
  ('Jusqu''a 4 000 kg', 'Up to 4,000 kg'),
  ('Aéronautique, spatial', 'Aeronautics, space'),
  ('Série M push-pull', 'M-series push-pull'),
  ('-55°C à +200°C', '-55°C to +200°C'),
  ('IE2 / IE3 selon version', 'IE2 / IE3 depending on version'),
  ('Triphasée 400 V AC (standard IEC)', 'Three-phase 400 V AC (IEC standard)'),
  ('110 / 240 / 450 Nm selon taille', '110 / 240 / 450 Nm depending on size'),
  ('0,5 – 190 Nm selon taille', '0.5 – 190 Nm depending on size'),
  ('0,25 – 15,8 kW selon taille', '0.25 – 15.8 kW depending on size'),
  ('Gestion et protection batterie', 'Battery management and protection'),
  ('Jusqu''a 2 000 kg', 'Up to 2,000 kg'),
  ('Jusqu''a 2 300 kg', 'Up to 2,300 kg'),
  ('6, 8 ou 10', '6, 8 or 10'),
  ('Intégration ROV, AUV, capteurs subsea', 'ROV, AUV and subsea sensor integration'),
  ('2, 3 ou 4', '2, 3 or 4'),
  ('Connecteur de puissance wet-mate', 'Wet-mate power connector'),
  ('Liaison batterie sur véhicules sous-marins', 'Battery link on underwater vehicles'),
  ('Jusqu''a 1,5 t', 'Up to 1.5 t'),
  ('Jusqu''a 500 kg', 'Up to 500 kg'),
  ('Intérim, CDD, CDI, management de transition', 'Temporary, fixed-term, permanent, interim management'),
  ('5 - 18 kW selon version', '5 - 18 kW depending on version'),
  ('Jusqu''a 90', 'Up to 90'),
  ('Jusqu''à 139 mNm', 'Up to 139 mNm'),
  ('Jusqu''à 12 300 tr/min', 'Up to 12,300 rpm'),
  ('Jusqu''à 2 760 mNm au décrochage, 171 mNm en continu', 'Up to 2,760 mNm stall, 171 mNm continuous'),
  ('Jusqu''à 18 000 tr/min, rendement 89 %', 'Up to 18,000 rpm, 89% efficiency'),
  ('8, 16 ou 19 mm', '8, 16 or 19 mm'),
  ('Standard, haute puissance, stérilisable (2 000 cycles), roulements céramique', 'Standard, high power, sterilizable (2,000 cycles), ceramic bearings'),
  ('Jusqu''à 120 000 tr/min', 'Up to 120,000 rpm'),
  ('30 bar (alcalin haute pression)', '30 bar (high-pressure alkaline)'),
  ('Jusqu''à 100 MW', 'Up to 100 MW'),
  ('Renouvelable, stockage, e-mobilité', 'Renewable, storage, e-mobility'),
  ('Chimie, gaz, agroalimentaire, cryogénie', 'Chemicals, gas, food processing, cryogenics'),
  ('Aérostructure, moteurs, compétition', 'Airframe structures, engines, motorsport'),
  ('5 axes, décolletage, rectification', '5-axis, screw machining, grinding'),
  ('De quelques kg a plusieurs centaines de kg', 'From a few kg to several hundred kg'),
  ('TRL 9 (a heritage de vol)', 'TRL 9 (flight heritage)'),
  ('19 l/min @ 70 bar', '19 L/min @ 70 bar'),
  ('Jusqu''à 15 kW', 'Up to 15 kW'),
  ('Jusqu''à 15 N·m', 'Up to 15 N·m'),
  ('Actionneur électromécanique', 'Electromechanical actuator'),
  ('Jusqu''à 400 bar', 'Up to 400 bar'),
  ('Basse puissance', 'Low power'),
  ('> 7000 unités livrées, en vol depuis 2014', '> 7,000 units delivered, flying since 2014'),
  ('jusqu''à 400 Am²', 'up to 400 Am²'),
  ('0,1 à 10 W', '0.1 to 10 W'),
  ('Magnetorqueur à barreau', 'Rod magnetorquer'),
  ('Désaturation roues de réaction', 'Reaction wheel desaturation'),
  ('Détermination d''attitude', 'Attitude determination'),
  ('> 1000 unités livrées, > 5 ans de fonctionnement en orbite LEO', '> 1,000 units delivered, > 5 years of operation in LEO'),
  ('Éprouvé en vol', 'Flight-proven'),
  ('Jusqu''à 35 N·m', 'Up to 35 N·m'),
  ('Industrie, maritime, défense, réseaux', 'Industry, marine, defense, grids'),
  ('Jusqu''a 8 000 W (mission 15 ans)', 'Up to 8,000 W (15-year mission)'),
  ('Jusqu''a 60', 'Up to 60'),
  ('12 ou 16 cellules en série (jusqu''à 60 V DC)', '12 or 16 cells in series (up to 60 V DC)'),
  ('Pilotage de contacteurs, E/S généralistes, communication contrôleur de stockage', 'Contactor control, general-purpose I/O, storage controller communication'),
  ('Électrique ou pneumatique', 'Electric or pneumatic'),
  ('Contrôle de fluides industriels', 'Industrial fluid control'),
  ('Antenne hélicoïdale déployable', 'Deployable helical antenna'),
  ('de 3 à 5 m, réflecteur métal-maille', '3 to 5 m, metal-mesh reflector'),
  ('Haute performance RF', 'High RF performance'),
  ('Très compact replié', 'Very compact when stowed'),
  ('Réflecteur déployable Wrapped Rib', 'Wrapped Rib deployable reflector'),
  ('Jusqu''à 2 000 mm', 'Up to 2,000 mm'),
  ('jusqu''à 210 bar', 'up to 210 bar'),
  ('Température ambiante, sans cryogénie, ordonnancement Slurm (QRMI)', 'Room temperature, no cryogenics, Slurm scheduling (QRMI)'),
  ('Atomes neutres, pièges optiques + excitation Rydberg', 'Neutral atoms, optical traps + Rydberg excitation'),
  ('QPL sur 50+ spécifications militaires, certifié ISO', 'QPL on 50+ military specifications, ISO certified'),
  ('Station sol robotisée', 'Robotic ground station'),
  ('85°C à 200°C selon conducteur', '85°C to 200°C depending on conductor'),
  ('Chaîne de traction électrique', 'Electric powertrain'),
  ('8 protocoles préprogrammés (Victron, SMA Sunny Island, Studer Innotec, Pylontech, etc.)', '8 preprogrammed protocols (Victron, SMA Sunny Island, Studer Innotec, Pylontech, etc.)'),
  ('5 à 16 cellules en série, 16-62 V DC', '5 to 16 cells in series, 16-62 V DC'),
  ('Résolution 19 mA @ ± 500 A', '19 mA resolution @ ± 500 A'),
  ('0,1 à 5,0 V, résolution 1 mV', '0.1 to 5.0 V, 1 mV resolution'),
  ('Convertisseur DC/DC isolé', 'Isolated DC/DC converter'),
  ('DIN rail, régulateur de commutation', 'DIN rail, switching regulator'),
  ('Fractional horsepower (FHP), châssis 48', 'Fractional horsepower (FHP), frame 48'),
  ('Couple constant, vitesse constante ou débit d''air constant selon modèle', 'Constant torque, constant speed or constant airflow depending on model'),
  ('NEMA et IEC', 'NEMA and IEC'),
  ('1/4 HP à plus de 5 000 HP', '1/4 HP to more than 5,000 HP'),
  ('120 V AC à 13,8 kV', '120 V AC to 13.8 kV'),
  ('Globetrotter — pilotable par variateur, jusqu''à 200 HP', 'Globetrotter — inverter-drivable, up to 200 HP'),
  ('IEEE 841 (usage critique, milieux sévères)', 'IEEE 841 (critical use, severe environments)'),
  ('2, 4 ou 6', '2, 4 or 6'),
  ('230/460 V (jusqu''à 30 HP) ou 460/575 V', '230/460 V (up to 30 HP) or 460/575 V'),
  ('Jusqu''a 20 vols', 'Up to 20 flights'),
  ('100 kW (15-80% en ~30 min)', '100 kW (15-80% in ~30 min)'),
  ('Double ou quadruple moteur', 'Dual or quad motor'),
  ('Jusqu''a 170 kg', 'Up to 170 kg'),
  ('Jusqu''à 8 000 N·m', 'Up to 8,000 N·m'),
  ('-30 à +70 °C', '-30 to +70 °C'),
  ('Jusqu''à 1500:1', 'Up to 1500:1'),
  ('Petite à grande série', 'Small to large series'),
  ('7 fonctions (6 degrés de liberté + pince)', '7 functions (6 degrees of freedom + gripper)'),
  ('Jusqu''à 250 kVA', 'Up to 250 kVA'),
  ('Cuivre/aluminium aéronautique', 'Aeronautical copper/aluminum'),
  ('-55 à +85 °C', '-55 to +85 °C'),
  ('Détection/identification automatique d''objets d''intérêt militaire', 'Automatic detection/identification of objects of military interest'),
  ('Imagerie satellite VHR (commerciale et gouvernementale)', 'VHR satellite imagery (commercial and government)'),
  ('-55 à +70 °C', '-55 to +70 °C'),
  ('Unité à petite/moyenne série', 'One-off to small/medium series'),
  ('Portable à industriel', 'Portable to industrial'),
  ('Jusqu''à 97 % (double conversion), 99 % (mode ECOnversion)', 'Up to 97% (double conversion), 99% (ECOnversion mode)'),
  ('Harnais sur mesure', 'Custom harness'),
  ('Sur mesure, câblage intégré', 'Custom, integrated wiring'),
  ('Défense, ferroviaire, aéronautique', 'Defense, rail, aeronautics'),
  ('Jusqu''à 300 Mbps (Rx) / 20 Mbps (Tx)', 'Up to 300 Mbps (Rx) / 20 Mbps (Tx)'),
  ('Facteur de bruit/G/T : 18,5 dB/K — EIRP : 48,4 dBW', 'Noise factor/G/T: 18.5 dB/K — EIRP: 48.4 dBW'),
  ('DVB-S2X, DVB-S2, DVB-RCS2 (voie retour sous licence)', 'DVB-S2X, DVB-S2, DVB-RCS2 (return channel under license)'),
  ('Défense, télécoms, énergie, médical, aéronautique, industrie', 'Defense, telecoms, energy, medical, aeronautics, industry'),
  ('-40 à +125 °C', '-40 to +125 °C'),
  ('Intégration et conseil technique', 'Integration and technical advice'),
  ('Variateur de fréquence triphasé, frein/ventilation 24 V en option', 'Three-phase frequency inverter, optional 24 V brake/ventilation'),
  ('0,5 – 95 Nm (jusqu''à 320 Nm sur CMP112)', '0.5 – 95 Nm (up to 320 Nm on CMP112)'),
  ('Jusqu''à 4,75 × couple statique', 'Up to 4.75 × static torque'),
  ('Interchangeable avec l''ancienne gamme DRE', 'Interchangeable with the former DRE range'),
  ('IP54 (IP55 à IP66 en option)', 'IP54 (IP55 to IP66 optional)'),
  ('0,8 – 2,1 kW (jusqu''à 6,3 kW en crête)', '0.8 – 2.1 kW (up to 6.3 kW peak)'),
  ('Jusqu''à 300 % selon configuration variateur', 'Up to 300% depending on inverter configuration'),
  ('Triphasée 380-480 V AC (standard industriel)', 'Three-phase 380-480 V AC (industrial standard)'),
  ('Moteur + réducteur + variateur intégrés', 'Motor + gearbox + inverter integrated'),
  ('380-500 V AC (ou variante 200-240 V AC)', '380-500 V AC (or 200-240 V AC variant)'),
  ('Auto, aéro, énergie, naval, spatial', 'Automotive, aerospace, energy, naval, space'),
  ('Spatial, aéro, ferroviaire, auto', 'Space, aerospace, rail, automotive'),
  ('Bureau d''études sur mesure', 'Custom design office'),
  ('Jusqu''a 800 kg', 'Up to 800 kg'),
  ('Jusqu''a 90 kg', 'Up to 90 kg'),
  ('Jusqu''a 350 kg', 'Up to 350 kg'),
  ('Jusqu''a 75 kg', 'Up to 75 kg'),
  ('12 à 50 V', '12 to 50 V'),
  ('Graphène courbé breveté', 'Patented curved graphene'),
  ('Production en série', 'Series production'),
  ('Numérique', 'Digital'),
  ('< 1 ms (capture image du Soleil)', '< 1 ms (Sun image capture)'),
  ('Capteur solaire fin numérique', 'Digital fine sun sensor'),
  ('Star tracker miniaturisé', 'Miniaturized star tracker'),
  ('Jusqu''à 4,8 Nm (12 V, plus élevé en 24 V)', 'Up to 4.8 Nm (12 V, higher at 24 V)'),
  ('Jusqu''à 750 mNm', 'Up to 750 mNm'),
  ('500 W – 20 kW (développement sur mesure)', '500 W – 20 kW (custom development)'),
  ('Jusqu''à 5,4 kW', 'Up to 5.4 kW'),
  ('Jusqu''à 96 %', 'Up to 96%'),
  ('37 – 70 mNm selon variante', '37 – 70 mNm depending on variant'),
  ('Indépendante par module', 'Independent per module'),
  ('Oui', 'Yes'),
  ('Hot/Cold (4 modules indép.)', 'Hot/Cold (4 independent modules)'),
  ('2 jeux redondants de gyroscope/accéléromètre 6-DDL + magnétomètre, bus CAN redondant', '2 redundant 6-DOF gyroscope/accelerometer sets + magnetometer, redundant CAN bus'),
  ('XYZ gyro + XYZ accél.', 'XYZ gyro + XYZ accel.'),
  ('CAN redondant / CSP', 'Redundant CAN / CSP'),
  ('2 microcontrôleurs indép.', '2 independent microcontrollers'),
  ('CAN + RS422 redondants', 'Redundant CAN + RS422'),
  ('1 000 mNms à 8 100 RPM', '1,000 mNms at 8,100 RPM'),
  ('-40 °C à +60 °C', '-40 °C to +60 °C'),
  ('Voûte céleste complète', 'Full celestial sphere'),
  ('EKF (Kalman étendu)', 'EKF (extended Kalman)'),
  ('10 kg à 200+ kg', '10 kg to 200+ kg'),
  ('FDIR Hiérarchique', 'Hierarchical FDIR'),
  ('Service géré', 'Managed service'),
  ('Developpe sous ESA Pioneer', 'Developed under ESA Pioneer'),
  ('3.3 à 5 V', '3.3 to 5 V'),
  ('Jusqu''a 700 km', 'Up to 700 km'),
  ('20-80% en 27 min', '20-80% in 27 min'),
  ('Jusqu''a 7 000 kg', 'Up to 7,000 kg'),
  ('Régie ou intérim', 'Time-and-materials or temporary'),
  ('Miniaturisée, basse consommation', 'Miniaturized, low power consumption'),
  ('10 kbps à 2 Mbps', '10 kbps to 2 Mbps'),
  ('2200-2290 MHz, +27 à +36 dBm', '2200-2290 MHz, +27 to +36 dBm'),
  ('Basse consommation', 'Low power consumption'),
  ('Haute stabilité temps-fréquence', 'High time-frequency stability'),
  ('10⁻¹⁰ par mois (100x meilleure qu''un OCXO)', '10⁻¹⁰ per month (100x better than an OCXO)'),
  ('Jusqu''à 8 A', 'Up to 8 A'),
  ('250A à 85°C (câble 50 mm²)', '250A at 85°C (50 mm² cable)'),
  ('Cloud privé ou sur site', 'Private cloud or on-premises'),
  ('Baffle et caméra séparés + unité de traitement dédiée', 'Separate baffle and camera + dedicated processing unit'),
  ('15 ans en GEO', '15 years in GEO'),
  ('Système optique réduit, unité de traitement intégrée', 'Reduced optical system, integrated processing unit'),
  ('COTS haute fiabilité', 'High-reliability COTS'),
  ('28V, 50V, 100V (régulé ou non régulé)', '28V, 50V, 100V (regulated or unregulated)'),
  ('500 W à 15 kW', '500 W to 15 kW'),
  ('Sequential Shunt Switching ou Maximum Power Point Tracking', 'Sequential Shunt Switching or Maximum Power Point Tracking'),
  ('Jusqu''a 650 kg', 'Up to 650 kg'),
  ('Flat-pack (jusqu''a 24 satellites/lancement)', 'Flat-pack (up to 24 satellites/launch)'),
  ('Commercial et industriel', 'Commercial and industrial'),
  ('10 W crête', '10 W peak'),
  ('-40 à +71 °C', '-40 to +71 °C'),
  ('12 h (batterie standard)', '12 h (standard battery)'),
  ('< 1 m (mode différentiel)', '< 1 m (differential mode)'),
  ('Tout-electrique, hybride ou tout-chimique au choix', 'All-electric, hybrid or all-chemical, as chosen'),
  ('Jusqu''a 516 km', 'Up to 516 km'),
  ('Jusqu''a 150 kW (80% en ~30 min)', 'Up to 150 kW (80% in ~30 min)'),
  ('Véhicules terrestres militaires, aéronefs, systèmes navals et missiles', 'Military land vehicles, aircraft, naval systems and missiles'),
  ('ISO 9001, AS9100 Rev D, accréditation NADCAP', 'ISO 9001, AS9100 Rev D, NADCAP accreditation'),
  ('Jusqu''à 1 500 kg', 'Up to 1,500 kg'),
  ('145 Nm continu / 350 Nm crête, 64 kW continu / 140 kW crête, rendement > 95 %, refroidi liquide', '145 Nm continuous / 350 Nm peak, 64 kW continuous / 140 kW peak, efficiency > 95%, liquid-cooled'),
  ('73 – 220 kW (300 – 700 kW en crête, configuration empilée)', '73 – 220 kW (300 – 700 kW peak, stacked configuration)'),
  ('Jusqu''à 96 %, densité de puissance > 7,2 kW/kg', 'Up to 96%, power density > 7.2 kW/kg'),
  ('400 V et plus', '400 V and above'),
  ('Jusqu''à 64 % vs moteur à induction CA (centrales de traitement d''air)', 'Up to 64% vs. AC induction motor (air handling units)'),
  ('Onduleur logiciel intégré, connecté IoT', 'Integrated software inverter, IoT-connected'),
  ('Réluctance commutée, sans terres rares ni cuivre rotor', 'Switched reluctance, no rare earths or rotor copper'),
  ('Sans soudure 3D', 'Solderless 3D'),
  ('10 - 150 kg selon plateforme', '10 - 150 kg depending on platform'),
  ('Jusqu''a 6 (Northrop Grumman GEM-63XL)', 'Up to 6 (Northrop Grumman GEM-63XL)'),
  ('Détection/géolocalisation RF mono-satellite', 'Single-satellite RF detection/geolocation'),
  ('Entraînement par courroie (BISG)', 'Belt drive (BISG)'),
  ('> 560 brevets déposés', '> 560 patents filed'),
  ('25 fois par seconde', '25 times per second'),
  ('3ème génération (SCALA 3)', '3rd generation (SCALA 3)'),
  ('500A / 50mV (extensible jusqu''à 10 000 A)', '500A / 50mV (expandable up to 10,000 A)'),
  ('-40 à +65 °C', '-40 to +65 °C'),
  ('Jusqu''a 560 km', 'Up to 560 km'),
  ('MEB (partagee avec ID.3, ID.7)', 'MEB (shared with ID.3, ID.7)'),
  ('100 V ou 120 V', '100 V or 120 V'),
  ('-55°C à +125°C', '-55°C to +125°C'),
  ('-55°C à +105°C', '-55°C to +105°C'),
  ('Jusqu''à 350 kW', 'Up to 350 kW'),
  ('jusqu''à 14 modules de puissance MPU-R3, 350 kW', 'up to 14 MPU-R3 power modules, 350 kW'),
  ('OCPP 1.6 et 2.0.1', 'OCPP 1.6 and 2.0.1'),
  ('CHAdeMO et CCS', 'CHAdeMO and CCS'),
  ('Interne, certifié ISO 26262', 'In-house, ISO 26262 certified'),
  ('Jusqu''à 300 Wh/L (refroidissement par immersion)', 'Up to 300 Wh/L (immersion cooling)'),
  ('Par immersion', 'Immersion'),
  ('Jusqu''à 345 W', 'Up to 345 W'),
  ('Jusqu''à 90 %', 'Up to 90%'),
  ('560 V DC (jusqu''à 750 V DC admissible)', '560 V DC (up to 750 V DC allowable)'),
  ('Industriel, ferroviaire, défense/avionique', 'Industrial, rail, defense/avionics'),
  ('Entièrement digital, intelligent', 'Fully digital, intelligent'),
  ('Robotique, aérospatial, suivi de mouvement', 'Robotics, aerospace, motion tracking'),
  ('UART, SPI, I²C, jusqu''à 1 kHz', 'UART, SPI, I²C, up to 1 kHz'),
  ('Béton, plâtre, terre crue, géopolymères', 'Concrete, plaster, raw earth, geopolymers'),
  ('Communications satellite, M2M/IoT', 'Satellite communications, M2M/IoT'),
  ('5-7 ans LEO, 20 kRad', '5-7 years LEO, 20 kRad'),
  ('Nova-C (NASA CLPS, atterrisseur lunaire)', 'Nova-C (NASA CLPS, lunar lander)'),
  ('GaAs multi-porteuse', 'Multi-carrier GaAs'),
  ('2 tiroirs (RF + alimentation)', '2 drawers (RF + power supply)'),
  ('Tension unique 5V', 'Single 5V voltage'),
  ('Zynq 7030/7045 dual-core (125K / 350K cellules FPGA)', 'Zynq 7030/7045 dual-core (125K / 350K FPGA cells)'),
  ('1GB DDR3 (512MB ECC), 1GB NVM, 32GB stockage, 256kB FRAM', '1GB DDR3 (512MB ECC), 1GB NVM, 32GB storage, 256kB FRAM'),
  ('ECC, formatage CCSDS', 'ECC, CCSDS formatting'),
  ('Agnilet, imprime 3D (LOX/RP-1)', 'Agnilet, 3D-printed (LOX/RP-1)'),
  ('Centrale inertielle 3 axes (FOG)', '3-axis inertial unit (FOG)'),
  ('Gyroscope a fibre optique', 'Fiber-optic gyroscope'),
  ('Gyroscope a fibre optique 3 axes', '3-axis fiber-optic gyroscope'),
  ('LEO optique & radar', 'Optical & radar LEO'),
  ('Capteur stellaire optique', 'Optical star tracker'),
  ('4,2 V / cellule', '4.2 V / cell'),
  ('Li-ion COTS qualifie spatial', 'Space-qualified COTS Li-ion'),
  ('Frein a induction passif', 'Passive induction brake'),
  ('Vibrations & chocs lanceur', 'Launcher vibration & shock'),
  ('Propulseurs a effet Hall', 'Hall-effect thrusters'),
  ('Conditionnement puissance EPS', 'EPS power conditioning'),
  ('Geostationnaire (36 000 km)', 'Geostationary (36,000 km)'),
  ('Earth observation, science, interplanetaire', 'Earth observation, science, interplanetary'),
  ('Alimentation unites lanceur / pyrotechnie', 'Launcher unit / pyrotechnic power supply'),
  ('Constellations LEO', 'LEO constellations'),
  ('GaN, controle numerique', 'GaN, digital control'),
  ('Controle integre', 'Integrated control'),
  ('100% electrique', '100% electric'),
  ('Triple jonction GaAs', 'GaAs triple-junction'),
  ('Propulseurs Hall / ioniques', 'Hall / ion thrusters'),
  ('Ultra-compacte, legere', 'Ultra-compact, lightweight'),
  ('Compacte, latch-up-free', 'Compact, latch-up-free'),
  ('Anneau collecteur (slip ring)', 'Slip ring'),
  ('Actionneur rotatif continu', 'Continuous rotary actuator'),
  ('Triple jonction', 'Triple-junction'),
  ('MDA AURORA (> 200 unites)', 'MDA AURORA (> 200 units)'),
  ('Panneau deployable', 'Deployable panel'),
  ('Externe, radiateur integre', 'External, integrated radiator'),
  ('Acquisition autonome', 'Autonomous acquisition'),
  ('Inter-satellite LEO/GEO', 'LEO/GEO inter-satellite'),
  ('NEMA taille 56', 'NEMA size 56'),
  ('> 6 000 cycles', '> 6,000 cycles'),
  ('Monomode/multimode', 'Single-mode/multimode'),
  ('500 heures', '500 hours'),
  ('200 kg (classe ESPA)', '200 kg (ESPA class)'),
  ('Hydrazine 6 DDL', 'Hydrazine 6 DOF'),
  ('Observation Terre optique/SAR, 5G satcom, ISR, edge computing', 'Optical/SAR Earth observation, 5G satcom, ISR, edge computing'),
  ('Vulcain 2.1 (1er etage) + Vinci (etage sup.), LH2/LOX', 'Vulcain 2.1 (1st stage) + Vinci (upper stage), LH2/LOX'),
  ('56 000 cellules/jour', '56,000 cells/day'),
  ('> 1 500 robots deployes, 25+ pays', '> 1,500 robots deployed, 25+ countries'),
  ('GEO, LEO, missions scientifiques', 'GEO, LEO, scientific missions'),
  ('New Space + institutionnel', 'New Space + institutional'),
  ('Coiffes, adaptateurs, structures, dispenseurs', 'Fairings, adapters, structures, dispensers'),
  ('24 pouces', '24 inches'),
  ('LMP tout-solide', 'All-solid-state LMP'),
  ('> 3 000 cycles', '> 3,000 cycles'),
  ('400 V AC (typique)', '400 V AC (typical)'),
  ('Monopropulseur vert HPGP', 'HPGP green monopropellant thruster'),
  ('Inox 316L', '316L stainless steel'),
  ('PVDF/Inox', 'PVDF/Stainless steel'),
  ('61,4 - 82,5 kWh (Blade LFP)', '61.4 - 82.5 kWh (Blade LFP)'),
  ('Immersion liquide', 'Liquid immersion'),
  ('PN, SN, localisation', 'PN, SN, location'),
  ('Automatique', 'Automatic'),
  ('500+ depuis 2010', '500+ since 2010'),
  ('Double redondance nominale/secours', 'Dual nominal/backup redundancy'),
  ('Flight-proven, autonomie panne', 'Flight-proven, autonomous fault handling'),
  ('Acquisition, compression, format', 'Acquisition, compression, formatting'),
  ('MIPI CSI-2 4 voies → Jetson', '4-lane MIPI CSI-2 → Jetson'),
  ('ESA / NASA scientifique', 'ESA / NASA scientific'),
  ('1M–30M symboles/s', '1M–30M symbols/s'),
  ('8,0–8,4 GHz (configurable vol)', '8.0–8.4 GHz (configurable in flight)'),
  ('~26 000 DMIPS / 2 TOPS INT8', '~26,000 DMIPS / 2 TOPS INT8'),
  ('7 ports RMAP 10–200 Mbps', '7 RMAP ports 10–200 Mbps'),
  ('Cartes filles PC/104', 'PC/104 daughter boards'),
  ('4× 64 bits + monitor (≈660 MHz)', '4× 64-bit + monitor (≈660 MHz)'),
  ('>4 000 DMIPS + AI', '>4,000 DMIPS + AI'),
  ('Satellites & instruments scientifiques', 'Scientific satellites & instruments'),
  ('>4 000 DMIPS', '>4,000 DMIPS'),
  ('ZeroFIT — flash FPGA, 0 scrubbing', 'ZeroFIT — FPGA flash, 0 scrubbing'),
  ('Instruments scientifiques', 'Scientific instruments'),
  ('Omni-P1 (CubeSat) → Omni-P3 (1 500 W)', 'Omni-P1 (CubeSat) → Omni-P3 (1,500 W)'),
  ('4× RISC-V 64 bits PolarFire SoC', '4× 64-bit RISC-V PolarFire SoC'),
  ('20 lanes : PCIe Gen2, 10G XFI', '20 lanes: PCIe Gen2, 10G XFI'),
  ('ZeroFIT flash FPGA, 0 scrubbing', 'ZeroFIT FPGA flash, 0 scrubbing'),
  ('ZeroFIT — 0 scrubbing requis', 'ZeroFIT — 0 scrubbing required'),
  ('Routage intra-satellite', 'Intra-satellite routing'),
  ('Agriculture, cartographie, env.', 'Agriculture, mapping, env.'),
  ('Monitoring, reset, sync horloge', 'Monitoring, reset, clock sync'),
  ('Translation / bridging multi-protocoles', 'Multi-protocol translation / bridging'),
  ('55 voies (version compacte)', '55 channels (compact version)'),
  ('25 canaux', '25 channels'),
  ('110 voies analogiques (thermistances, RTD)', '110 analog channels (thermistors, RTD)'),
  ('45 jours autonome', '45 days standalone'),
  ('Centre technique industriel', 'Industrial technical center'),
  ('13 pays', '13 countries'),
  ('1535–1565 nm (bande C)', '1535–1565 nm (C band)'),
  ('Espace, astronomie, recherche', 'Space, astronomy, research'),
  ('+8 Ethernet 1G / +9 alimentation', '+8 1G Ethernet / +9 power supply'),
  ('Ethernet 1G, 8 ports', '1G Ethernet, 8 ports'),
  ('8x emplacements SSD, RAID ajustable', '8x SSD slots, adjustable RAID'),
  ('Liquide', 'Liquid'),
  ('NMC marine', 'Marine NMC'),
  ('Capteur solaire fin', 'Fine sun sensor'),
  ('6 semaines', '6 weeks'),
  ('16 unites lancees (depuis 2020)', '16 units launched (since 2020)'),
  ('CubeSat (format nano)', 'CubeSat (nano format)'),
  ('CubeSat (format pico)', 'CubeSat (pico format)'),
  ('Batterie thermique', 'Thermal battery'),
  ('Ferroviaire exigeant', 'Demanding rail applications'),
  ('Acier carbone/inox', 'Carbon/stainless steel'),
  ('70 kW (Toyota) + batterie LFP', '70 kW (Toyota) + LFP battery'),
  ('Successeur ICARE-NG2', 'ICARE-NG2 successor'),
  ('Transistor GaN (GaNFET)', 'GaN transistor (GaNFET)'),
  ('Module CPU', 'CPU module'),
  ('Module FPGA', 'FPGA module'),
  ('Rapide, multi-missions', 'Fast, multi-mission'),
  ('> 2 400 modules', '> 2,400 modules'),
  ('Ku (utilisateurs) / Ka (passerelles)', 'Ku (users) / Ka (gateways)'),
  ('Double CAN 2.0B, protocole OBD2', 'Dual CAN 2.0B, OBD2 protocol'),
  ('Petits satellites, transfert orbital', 'Small satellites, orbital transfer'),
  ('Electrique ExoMG (Exotrail)', 'ExoMG electric (Exotrail)'),
  ('Usinage 3/4/5/9 axes', '3/4/5/9-axis machining'),
  ('Liquide actif', 'Active liquid'),
  ('Allemagne, production propre', 'Germany, in-house production'),
  ('3,3 – 3,6 V, courant 40-120 mA', '3.3 – 3.6 V, current 40-120 mA'),
  ('Li-ion NMC grade spatial', 'Space-grade NMC Li-ion'),
  ('Li-ion grade spatial', 'Space-grade Li-ion'),
  ('Gyroscope MEMS 6 axes', '6-axis MEMS gyroscope'),
  ('GPS/INS hybride', 'Hybrid GPS/INS'),
  ('Utilisateurs, prescripteurs, installateurs', 'Users, specifiers, installers'),
  ('ARM9 32 bits, 400 MHz', '32-bit ARM9, 400 MHz'),
  ('650 km (5 plans, 5 satellites/plan)', '650 km (5 planes, 5 satellites/plane)'),
  ('28 combinaisons taille/empilement, 120 bobinages', '28 size/stack combinations, 120 windings'),
  ('7 ans (orbite SSO 750 km)', '7 years (750 km SSO orbit)'),
  ('5,5 – 45 kW (gamme m500 IE3, fonctionnement variateur)', '5.5 – 45 kW (m500 IE3 range, inverter operation)'),
  ('4 tonnes H2/jour', '4 tonnes H2/day'),
  ('Connecteur circulaire wet-mate', 'Circular wet-mate connector'),
  ('Optique infrarouge', 'Infrared optics'),
  ('18 / 24 / 36 / 48 V (plage 15-48 V)', '18 / 24 / 36 / 48 V (range 15-48 V)'),
  ('Acier inoxydable', 'Stainless steel'),
  ('Vanne latch bistable', 'Bistable latching valve'),
  ('Heliosynchrone, ~ 550 km', 'Sun-synchronous, ~550 km'),
  ('> 1 kW (moyenne orbitale)', '> 1 kW (orbit average)'),
  ('> 1 000 000 cycles', '> 1,000,000 cycles'),
  ('~ 100 milliards NTC/cm²', '~100 billion NTC/cm²'),
  ('Quelques secondes', 'A few seconds'),
  ('> 5 000 cycles', '> 5,000 cycles'),
  ('Capteur solaire', 'Sun sensor'),
  ('Encodeur 23 bits', '23-bit encoder'),
  ('Satellite, lanceur', 'Satellite, launch vehicle'),
  ('Lanceur', 'Launch vehicle'),
  ('Satellite, lanceur, rover', 'Satellite, launch vehicle, rover'),
  ('Thermistances NTC 10 kΩ @ 25°C', 'NTC thermistors 10 kΩ @ 25°C'),
  ('Geostationnaire', 'Geostationary'),
  ('Communication smallsat', 'Smallsat communication'),
  ('Minimisation masse/volume', 'Mass/volume minimization'),
  ('Montage DIN rail', 'DIN rail mounting'),
  ('Alimentation industrielle', 'Industrial power supply'),
  ('Alimentation industrielle compacte', 'Compact industrial power supply'),
  ('~ 676 km (420 mi, batterie 149 kWh)', '~676 km (420 mi, 149 kWh battery)'),
  ('Bande S', 'S-band'),
  ('Bande C', 'C-band'),
  ('Moteur Curie', 'Curie engine'),
  ('500-800 VDC (option 110 VAC)', '500-800 VDC (110 VAC option)'),
  ('1 MWh / conteneur', '1 MWh / container'),
  ('Marine, solaire, secours', 'Marine, solar, backup'),
  ('> 2 000 cycles', '> 2,000 cycles'),
  ('Connecteurs, fusibles, filtres', 'Connectors, fuses, filters'),
  ('Chiffrement AES-256, SecureBoot', 'AES-256 encryption, SecureBoot'),
  ('5 (France + Maroc)', '5 (France + Morocco)'),
  ('Aimants permanents (synchrone)', 'Permanent magnets (synchronous)'),
  ('Arnhem Space Centre (Australie)', 'Arnhem Space Centre (Australia)'),
  ('Tout-electrique avancee', 'Advanced all-electric'),
  ('Tout-electrique', 'All-electric'),
  ('12 V / 24 V (automobile)', '12 V / 24 V (automotive)'),
  ('0,46 – 3,8 A (alimentation via driver externe)', '0.46 – 3.8 A (powered via external driver)'),
  ('NEMA 23 (57,2 mm)', 'NEMA 23 (57.2 mm)'),
  ('ESPA (adaptateur demi-plaque)', 'ESPA (half-plate adapter)'),
  ('T&C, GNC, payload critique', 'T&C, GNC, critical payload'),
  ('28 V (plage 9–33,6 V)', '28 V (range 9–33.6 V)'),
  ('≤ 0,3°/s (perf. nominale)', '≤ 0.3°/s (nominal perf.)'),
  ('Arcseconde', 'Arcsecond'),
  ('5 clients europeens', '5 European customers'),
  ('2 (1er etage reutilisable)', '2 (reusable 1st stage)'),
  ('9 moteurs Merlin, RP-1/LOX', '9 Merlin engines, RP-1/LOX'),
  ('Depuis 1988', 'Since 1988'),
  ('7 moteurs GNL/LOX', '7 LNG/LOX engines'),
  ('Applications hautement corrosives', 'Highly corrosive applications'),
  ('Mini/Micro/Cube/Nanosatellites LEO', 'LEO Mini/Micro/Cube/Nanosatellites'),
  ('Micro horloge atomique', 'Micro atomic clock'),
  ('20° circulaire', '20° circular'),
  ('64,0 kWh brut (LFP)', '64.0 kWh gross (LFP)'),
  ('5,5 tonnes', '5.5 tonnes'),
  ('Batterie lithium-ion 48V, convertisseur DC/DC', '48V lithium-ion battery, DC/DC converter'),
  ('Wemding, Allemagne', 'Wemding, Germany'),
  ('> 150 000 (depuis 2017)', '> 150,000 (since 2017)'),
  ('12 V (sortie simple)', '12 V (single output)'),
  ('DC/DC bidirectionnel', 'Bidirectional DC/DC'),
  ('AC/DC unidirectionnel / bidirectionnel', 'Unidirectional / bidirectional AC/DC'),
  ('Bornes DC fast charging', 'DC fast-charging stations'),
  ('Quelques semaines', 'A few weeks'),
  ('Centrale inertielle (IMU)', 'Inertial measurement unit (IMU)'),
  ('> 25 (10+ pays)', '> 25 (10+ countries)')
) AS v(fr, en)
WHERE s.value = v.fr
  AND s.value_en IS NULL;

-- Contrôle : lignes de caractéristiques avec une valeur traduite.
SELECT count(*) FILTER (WHERE value_en IS NOT NULL) AS valeurs_traduites, count(*) AS total_lignes FROM product_specs;
